## Instructions
* Read each cell and implement the **TODOs** sequentially. The markdown/text cells also contain instructions which you need to follow to get the whole notebook working.
* Do not change the variable names unless the instructor allows you to.
* Do not delete the **TODO** comment blocks.
* Aside from the TODOs, there will be questions embedded in the notebook and a cell for you to provide your answer (denoted with A:). Answer all the markdown/text cells with **"A: "** on them. 
* You are expected to search how to some functions work on the Internet or via the docs. 
* You may add new cells for "scrap work".
* The notebooks will undergo a "Restart and Run All" command, so make sure that your code is working properly.
* You are expected to understand the data set loading and processing separately from this class.
* You may not reproduce this notebook or share them to anyone.

# Assignment 2.1 - Natural Language Processing Notebook 
In this notebook, you will be asked to implement a simple n-gram based spell checker and a simple tf-idf based document retrieval.

In [138]:
import numpy as np
import requests
import re
import os
from tqdm import tqdm
import glob
import pandas as pd
import nltk
from nltk.metrics import distance



# Simple N-gram based Spell Checker

The assignment will help you understand how language models and probabilistic methods can be applied to the task of spelling correction.

To implement a spell checker, you will need to first identify and suggest corrections for misspelled words. 
When a word is flagged as potentially misspelled, your program will compare it against the n-gram model, generate a list of possible corrections based on the highest n-gram similarity scores, and suggest the most probable corrections to the user.

### Creating the N-gram model

As a simplification, you will not be creating the n-gram model from scratch. Instead, we will be utilizing a publicly available n-gram frequency counts for the english language.

Source: Multi-Lex (https://analytics.huma-num.fr/popr-ngram/Multi-LEX/index.html)

Let's load the 2-gram csv.

In [139]:
df_bigram = pd.read_csv("ENG2_million.csv", delimiter="\t")
df_bigram

,NGRAM,GRAM1,GRAM2,POS1,POS2,OCCURRENCE,FPM,ZFI,POS_PC
0,to be,to,be,prt,verb,47783417,3.113632,7.255341,100.000000
1,it is,it,is,pron,verb,36860809,3.000920,7.104395,100.000000
2,it was,it,was,pron,verb,35600591,2.985812,7.084163,100.000000
3,do not,do,not,verb,adv,27042969,2.866409,6.924258,100.000000
4,did not,did,not,verb,adv,25077663,2.833642,6.880376,99.997472
...,...,...,...,...,...,...,...,...,...
999995,to surname,to,surname,prt,verb,125,-2.468735,-0.220617,91.200000
999996,familiar analogy,familiar,analogy,adj,noun,226,-2.211537,0.123825,100.000000
999997,technical arrangements,technical,arrangements,adj,noun,879,-1.621656,0.913799,100.000000
999998,winch were,winch,were,noun,verb,50,-2.866675,-0.753542,100.000000
999999,claims based,claims,based,noun,verb,8317,-0.645679,2.220837,98.641337

This csv provides a million 2-gram pairs. So you will need to handle words that are missing.

The columns are as follows: <br />
- NGRAM: The pair of words <br />
- GRAM1 and GRAM2: Each of the words separated <br />
- POS1 and POS2: Part of speech tags of each word<br />
- Occurrence : Number of times a sequence was read in the corpus. <br/>
- FPM : Frequency Per Million occurrence. <br/>
- ZFI : Standardized Frequency Index. <br/>

For convenience, we can use a dictionary data structure to store the 2-gram frequency counts.

In [140]:
#Since the data is very large 
#I am testing my logic first with a smaller self created dataframe
import pandas as pd 
# Create a sample dataframe 
data = { 
    'GRAM1': ['hello', 'hello', 'good', 'good', 'nice'], 
    'GRAM2': ['world', 'there', 'morning', 'evening', 'day'], 
    'OCCURRENCE': [10, 5, 20, 15, 8] 
    } 

# Convert the data dictionary into a pandas dataframe 
df_test = pd.DataFrame(data) 

# Display the dataframe 
df_test

   GRAM1    GRAM2  OCCURRENCE
0  hello    world          10
1  hello    there           5
2   good  morning          20
3   good  evening          15
4   nice      day           8

In [141]:
# Initialize the dictionary
bi_gram_dict = {}

# Iterate over rows of the dataframe
for _, row in df_test.iterrows():
    word1 = row['GRAM1']
    word2 = row['GRAM2']
    occurrence = row['OCCURRENCE']
    
    # If the first word is not in the dictionary, add it
    if word1 not in bi_gram_dict:
        bi_gram_dict[word1] = {}
    
    # Add the second word and its frequency count to the nested dictionary
    bi_gram_dict[word1][word2] = occurrence
bi_gram_dict

{'hello': {'world': 10, 'there': 5},
 'good': {'morning': 20, 'evening': 15},
 'nice': {'day': 8}}

In [104]:
bi_gram_dict = {}
############################################################
# TODO-01: Convert the n-gram counts from the pandas       #
# dataframe to a dictionary where                          #
# bi_gram_dict[word1][word2] gives the frequency count of  #
# the pair of words.                                       #
############################################################

# Iterate over rows of the dataframe
for _, row in df_bigram.iterrows():
    word1 = row['GRAM1']
    word2 = row['GRAM2']
    occurrence = row['OCCURRENCE']
    
    # If the first word is not in the dictionary, add it
    if word1 not in bi_gram_dict:
        bi_gram_dict[word1] = {}
    
    # Add the second word and its frequency count to the nested dictionary
    bi_gram_dict[word1][word2] = occurrence


############################################################
#                    End of your code.                     #
############################################################

Next, we want to get a list of english words to serve as our vocabulary. But since the n-gram provided above is not complete, we will get the vocabulary list from the Brown corpus instead.

In [105]:
from nltk.corpus import brown
nltk.download('brown')
print(brown.readme())

BROWN CORPUS

A Standard Corpus of Present-Day Edited American
English, for use with Digital Computers.

by W. N. Francis and H. Kucera (1964)
Department of Linguistics, Brown University
Providence, Rhode Island, USA

Revised 1971, Revised and Amplified 1979

http://www.hit.uib.no/icame/brown/bcm.html

Distributed with the permission of the copyright holder,
redistribution permitted.

[nltk_data] Downloading package brown to
[nltk_data]     C:\Users\ningw\AppData\Roaming\nltk_data...
[nltk_data]   Package brown is already up-to-date!

We can get all the words through the function ``.words()``.

In [106]:
print("List of words", brown.words())
print("Number of words", len(brown.words()))

List of words ['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', ...]
Number of words 1161192

As you can see, the vocabulary or list of words contain both uppercase and lowercase letters. 
But we only want lowercase letters. Therefore, we first need to convert the vocabulary to lowercase letters. 

Hint: the ``set()`` function of python can be useful for this.

In [107]:
############################################################
# TODO-02: Convert the words to lowercase and get all the  #
# unique words into the variable vocabulary_lowercased.    #
############################################################


# Extract words, lowercase them, and find unique words
vocabulary_lowercased = set(word.lower() for word in brown.words())


############################################################
#                    End of your code.                     #
############################################################
N_vocab = len(vocabulary_lowercased)
print("Number of unique words in the vocabulary", N_vocab)

Number of unique words in the vocabulary 49815

Implement the function to compute for the 2-gram probability with Laplace smoothing.

Recall that the formula for the standard 2-gram is:
$$P(w_n | w_{n-1}) = \frac{\text{count}(w_{n-1}w_n)}{\sum_{w^\prime} \text{count}(w_{n-1}w^\prime)} = \frac{\text{count}(w_{n-1}w_n)}{\text{count}(w_{n-1})}$$

To apply Laplace smoothing, we simply add one to the counts resulting to the following formula, where $V$ is the vocabulary size:
$$P_{\text{Laplace}}(w_n | w_{n-1}) = \frac{\text{count}(w_{n-1}w_n) + 1}{\sum_{w^\prime} \text{count}(w_{n-1}w^\prime) + 1} = \frac{\text{count}(w_{n-1}w_n) + 1}{\text{count}(w_{n-1}) + V}$$

In [108]:
############################################################
# TODO-03: Implement the function that computes for the    #
# laplace smoothed bi-gram probabilities. Since the bi-    #
# gram model is incomplete (only a million rows), you      #
# would need to handle the words that do not appear in the #
# bi-gram model at all. For simplicity, you can just       #
# assign it a very low probability (e.g. 1e-10)            #
############################################################
def bi_gram_probability(word1, word2, bi_gram_dict):
    """
    Computes the bi-gram probability using a nested dictionary and Laplace smoothing.

    Args:
    - word1: The first word in the bi-gram.
    - word2: The second word in the bi-gram.
    - bi_gram_dict: Nested dictionary where bi_gram_dict[word1][word2] gives the count.

    Returns:
    - Smoothed probability of the bi-gram (word1, word2).
    """
    # Define a low probability for unseen bi-grams
    low_probability = 1e-10

    # Extract vocabulary size (number of unique second words in all word1 keys)
    vocabulary_size = sum(len(word_dict) for word_dict in bi_gram_dict.values())

    # Check if word1 exists in the dictionary
    if word1 in bi_gram_dict:
        # Get the count for the bi-gram (word1, word2)
        bigram_count = bi_gram_dict[word1].get(word2, 0)

        # Compute the total count of bi-grams starting with word1
        unigram_count = sum(bi_gram_dict[word1].values())

        # Apply Laplace smoothing
        probability = (bigram_count + 1) / (unigram_count + vocabulary_size)
        return probability

    # If word1 is not found, return the low probability
    return low_probability


############################################################
#                    End of your code.                     #
############################################################

In [109]:
# Example nested bi-gram dictionary
bi_gram_dict = {
    "the": {"cat": 5, "dog": 2},
    "cat": {"sat": 3, "barked": 1},
    "dog": {"barked": 4}
}

# Compute probabilities
prob1 = bi_gram_probability("the", "cat", bi_gram_dict)
prob2 = bi_gram_probability("cat", "barked", bi_gram_dict)
prob3 = bi_gram_probability("dog", "meowed", bi_gram_dict)  # Unseen bi-gram
prob4 = bi_gram_probability("bird", "flew", bi_gram_dict)  # Unseen first word

print("Probability of ('the', 'cat'):", prob1)
print("Probability of ('cat', 'barked'):", prob2)
print("Probability of ('dog', 'meowed'):", prob3)
print("Probability of ('bird', 'flew'):", prob4)

Probability of ('the', 'cat'): 0.5
Probability of ('cat', 'barked'): 0.2222222222222222
Probability of ('dog', 'meowed'): 0.1111111111111111
Probability of ('bird', 'flew'): 1e-10

### Implementing the Spell Checker components

For the spell checker, we would need to first pre-process the text and identify the potentially misspelled words.

In [110]:
###############################################################
# TODO-04: Implement the function that pre-processes the text #
# such as converting to lowercase and removing all symbols    #
# or punctuation marks. The function returns the              #
# preprocessed string.                                        #
###############################################################

def preprocess_text(text):
    """
    Preprocesses the text by converting to lowercase and removing all symbols/punctuation.

    Args:
    - text: The input string.

    Returns:
    - The preprocessed string.
    """
    # Convert text to lowercase
    text = text.lower()

    # Use regular expressions to remove all symbols (non-alphanumeric characters)
    text = re.sub(r'[^\w\s]', '', text)  # Removes anything that's not a word or whitespace

    # Remove extra spaces or newlines (optional)
    text = text.strip()  # Strips leading and trailing spaces

    return text

# Example usage
sample_text = "Hello, World! This is a@$%@!%^& test, right? Let's preprocess this: text."
clean_text = preprocess_text(sample_text)

print("Original Text:", sample_text)
print("Preprocessed Text:", clean_text)


##############################################################
#                    End of your code.                       #
##############################################################

Original Text: Hello, World! This is a@$%@!%^& test, right? Let's preprocess this: text.
Preprocessed Text: hello world this is a test right lets preprocess this text

In [111]:
###############################################################
# TODO-05: Implement the function that checks if the word is  #
# potentially misspelled. It should return True if            #
# misspelled and False otherwise.                             #
###############################################################

def is_misspelled(word, vocab):
    """
    Checks if the given word is misspelled based on the provided vocabulary list.

    Args:
        word (str): The word to check.
        vocab (set): A set of correctly spelled words.

    Returns:
        bool: True if the word is misspelled, False otherwise.
    """
    # Preprocess both the word and vocabulary
    processed_word = preprocess_text(word)
    processed_vocab = {preprocess_text(v) for v in vocab}

    # Check if the word exists in the preprocessed vocabulary
    return processed_word not in processed_vocab

# Example usage
vocab = {"Hello,", "World!", "Python", "Code.", "function", "misspelled"}
word1 = "Function"
word2 = "misspellded"
word3 = "Code"
word4 = "worldd"

print("Word:", word1, "- Misspelled:", is_misspelled(word1, vocab))  # Output: False
print("Word:", word2, "- Misspelled:", is_misspelled(word2, vocab))  # Output: True
print("Word:", word3, "- Misspelled:", is_misspelled(word3, vocab))  # Output: False
print("Word:", word4, "- Misspelled:", is_misspelled(word4, vocab))  # Output: True


###############################################################
#                    End of your code.                        #
###############################################################

Word: Function - Misspelled: False
Word: misspellded - Misspelled: True
Word: Code - Misspelled: False
Word: worldd - Misspelled: True

For convenience of computing the n-grams later on, we also want to get the surrounding k words before and after the misspelled word. A possible way to structure this is shown below.
```
[
    {
        "word": ...,
        "before": ...,
        "after": ...,
    },
    ...
]
```

In [112]:
############################################################
# TODO-06: Implement the function that gets all the        #
# misspelled words in the provided text. Returns a list of #
# {"word":..., "before":..., "after":...}                  #
############################################################

def get_all_misspelled_words(text, vocab):
    """
    Finds all misspelled words in the text and provides context.

    Args:
    - text: The input string to check.
    - vocab: A set of correctly spelled words.

    Returns:
    - A list of dictionaries containing misspelled words and context.
    """
    # Preprocess the text
    preprocessed_text = preprocess_text(text)

    # Split text into words
    words = preprocessed_text.split()

    # Initialize result list
    result = []

    # Iterate over words to find misspelled ones
    for i, word in enumerate(words):
        if is_misspelled(word, vocab):
            before = words[i - 1] if i > 0 else None  # Previous word
            after = words[i + 1] if i < len(words) - 1 else None  # Next word
            result.append({"word": word, "before": before, "after": after})

    return result

# Example usage
text = "Hello, this is a sampl text with misspelled wrds and incomplete vocbulary."
vocab = {"hello", "this", "is", "a", "sample", "text", "with", "and", "incomplete", "misspelled"}

list_misspelled_words = []
misspelled_words = get_all_misspelled_words(text, vocab)

print("Misspelled Words:")
for item in misspelled_words:
    list_misspelled_words.append(item)

print(list_misspelled_words)

    
############################################################
#                    End of your code.                     #
############################################################

Misspelled Words:
[{'word': 'sampl', 'before': 'a', 'after': 'text'}, {'word': 'wrds', 'before': 'misspelled', 'after': 'and'}, {'word': 'vocbulary', 'before': 'incomplete', 'after': None}]

For each of the misspelled word, we need to generate a list of candidate words that could potentially be the correct word. To do this, we want to get all the words with at most $k$ edit distance from the misspelled word.

Look up the function: ``distance.edit_distance`` 

https://www.nltk.org/api/nltk.metrics.distance.html#nltk.metrics.distance.edit_distance

For now, lets use $k=2$.

In [113]:
############################################################
# TODO-07: Implement the function that gets all candidate  #
# words that are at most k edit distance from the given    #
# word. Return a list of candidate words.                  #
############################################################

from nltk.metrics import edit_distance

def get_candidate_words(word, vocab, k):
    """
    Finds all candidate words in the vocabulary that are at most k edit distance from the given word.

    Args:
    - word: The input word.
    - vocab: A set of correctly spelled words.
    - k: The maximum allowed edit distance.

    Returns:
    - A list of candidate words that are within k edit distance of the given word.
    """
    # Initialize a list to store candidate words
    candidates = []

    # Iterate over each word in the vocabulary
    for v in vocab:
        # Calculate edit distance using NLTK
        distance = edit_distance(word, v)
        # Include the word if its edit distance is <= k
        if distance <= k:
            candidates.append(v)

    return candidates

# Example Usage
vocab = {"hello", "world", "python", "coding", "programming"}
word = "codng"
k = 1

# Find candidates
candidates = get_candidate_words(word, vocab, k)
print("Word:", word)
print("Candidates:", candidates)

word = "pythno"
k = 2  # Allow up to 2 edits

# Find candidates
candidates = get_candidate_words(word, vocab, k)
print("Word:", word)
print("Candidates:", candidates)

# Example usage
vocab = {"coding", "caring", "cargo", "card", "cord", "curve", "corn"}
word = "crd"

# Find candidates within 3 edits
candidates = get_candidate_words(word, vocab, k=3)
print("Word:", word)
print("Candidates:", candidates)
############################################################
#                    End of your code.                     #
############################################################

Word: codng
Candidates: ['coding']
Word: pythno
Candidates: ['python']
Word: crd
Candidates: ['corn', 'cord', 'curve', 'cargo', 'card']

Lastly, we want to get the top $k$ suggested corrections ranked based on the n-gram probabilities. For this you can compute two kinda of probabilities based on the context or surrounding words: the probability of the corrected word coming after the previous word and before the next word. For simplicity, you can add the two probabilities.

In [114]:
############################################################
# TODO-08: Implement the function that gets the top k      #
# suggested corrections based on the n-gram probabilities  #
# with the surrounding words. Return the word and its      #
# corresponding probability.                               #
############################################################

def get_top_k_corrections(prev_word, next_word, candidates, ngram_model, k):
    """
    Get the top k suggested corrections based on the n-gram probabilities using a nested dictionary model.

    Parameters:
        context (tuple): A tuple containing the previous word and the next word.
        candidates (list): A list of candidate words to consider as corrections.
        ngram_model (dict): A nested dictionary representing the n-gram probabilities.
                            Format: {prev_word: {candidate: probability}, candidate: {next_word: probability}}
        k (int): Number of top suggestions to return.

    Returns:
        list: A list of tuples where each tuple contains a candidate word and its corresponding probability.
    """
    prev_word, next_word
    suggestions = []

    for candidate in candidates:
        # Compute the combined probability
        prob_after_prev = ngram_model.get(prev_word, {}).get(candidate, 0)
        prob_before_next = ngram_model.get(candidate, {}).get(next_word, 0)
        combined_prob = prob_after_prev + prob_before_next

        # Add to suggestions
        suggestions.append((candidate, combined_prob))
    
    # Sort suggestions by probability in descending order
    suggestions.sort(key=lambda x: x[1], reverse=True)
    
    # Return the top k suggestions
    return suggestions[:k]


# Example nested n-gram model
ngram_model = {
    'the': {'cat': 0.3, 'dog': 0.2},
    'cat': {'sat': 0.25},
    'dog': {'sat': 0.15},
}

# Context: previous word and next word
prev_word = "the"
next_word = "sat"

# Candidate corrections
candidates = ['cat', 'dog', 'rat']

# Get top 2 corrections
top_corrections = get_top_k_corrections(prev_word, next_word, candidates, ngram_model, k=2)
print("Example 1")
print(top_corrections)
print()
print("Example 2")

# Far more complicated example with a detailed nested n-gram model
ngram_model = {
    'the': {
        'quick': 0.4, 'lazy': 0.3, 'brown': 0.1
    },
    'quick': {
        'fox': 0.35, 'dog': 0.1, 'cat': 0.05
    },
    'lazy': {
        'dog': 0.25, 'fox': 0.1, 'hamster': 0.05
    },
    'brown': {
        'fox': 0.45, 'bear': 0.2, 'dog': 0.15
    },
    'fox': {
        'jumps': 0.5, 'runs': 0.3, 'sleeps': 0.2
    },
    'dog': {
        'sleeps': 0.4, 'barks': 0.3, 'runs': 0.2
    },
    'cat': {
        'meows': 0.35, 'pounces': 0.25, 'sleeps': 0.2
    },
}

# Context: previous word and next word
prev_word = "the"
next_word = "sat"

# Candidate corrections to evaluate
candidates = ['quick', 'lazy', 'brown', 'fox', 'dog', 'cat']

# Function call to find top 3 suggestions
top_corrections = get_top_k_corrections(prev_word, next_word, candidates, ngram_model, k=3)
print(top_corrections)


############################################################
#                    End of your code.                     #
############################################################

Example 1
[('cat', 0.55), ('dog', 0.35)]

Example 2
[('quick', 0.4), ('lazy', 0.3), ('brown', 0.1)]

Tying it all up, we now want to implement the spelling correction function that outputs the list of suggested corrections for each of the misspelled words.

We want this to be in the format shown below:
```
[
    {
        "misspelled_word": ...,
        "suggested_corrections": [...],
        "probabilities": [...],
    }
]
```

In [115]:
############################################################
# TODO-09: Implement a function that outputs the list of   #
# misspelled words and the suggested corrections together  #
# with its probabilities.                                  #
############################################################

def spelling_suggestions(sentence, vocab, m, ngram_model, k):
    """
    Generates spelling suggestions for misspelled words in a given sentence.

    Args:
        sentence (str): The input sentence.
        vocab (set): The set of correct vocabulary words.
        m (int): The maximum edit distance for candidate generation.
        ngram_model (dict): The n-gram model for context evaluation.
        k (int): The number of top corrections to return.

    Returns:
        list: A list of dictionaries containing misspelled words, their suggestions, and probabilities.
    """
    result = []

    # Preprocess sentence and identify misspelled words
    sentence = preprocess_text(sentence)
    misspelled = get_all_misspelled_words(sentence, vocab)

    # Extract contextual information for misspelled words
    prev_word = [misspelled_word.get("before") for misspelled_word in misspelled]
    word = [misspelled_word.get("word") for misspelled_word in misspelled]
    next_word = [misspelled_word.get("after") for misspelled_word in misspelled]

    # Generate suggestions for each misspelled word
    for i, w in enumerate(word):
        candidates = get_candidate_words(w, vocab, m)
        suggestions = get_top_k_corrections(prev_word[i], next_word[i], candidates, ngram_model, k)

        suggested = [s[0] for s in suggestions]
        prob = [s[1] for s in suggestions]
        
        # Safeguard against division by zero
        total_prob = sum(prob)
        normalized_prob = [p / total_prob for p in prob] if total_prob > 0 else [0 for _ in prob]

        temp_dict = {
            "misspelled_word": w,
            "suggested_corrections": suggested,
            "probabilities": normalized_prob
        }
        result.append(temp_dict)

    return result
    
    
# Example usage
m = 2
k = 3
sentence = "The quick brwn fox jmps over the lazy dgs."

vocab = {
    "the", "quick", "brown", "fox", "jumps", "over", "lazy", "dogs", "bran"
}

ngram_model = {
    'the': {
        'quick': 0.5, 'lazy': 0.5
    },
    'test': { 
        'brown': 0.75
        },
    'quick': {
        'brown': 0.5,
        'bran': 0.5
    },
    'brown': {
        'fox': 0.75,
        'dog': 0.25,
    'bran': {
        'fox': 0.5
    },
    },
    'fox': {
        'jumps': 1.0
    },
    'jumps': {
        'over': 1.0
    },
    'over': {
        'the': 1.0
    },
    'lazy': {
        'dogs': 1.0
    }
}

ans = spelling_suggestions(sentence, vocab, m, ngram_model, k)
ans
############################################################
#                    End of your code.                     #
############################################################

[{'misspelled_word': 'brwn',
  'suggested_corrections': ['brown', 'bran'],
  'probabilities': [0.7142857142857143, 0.2857142857142857]},
 {'misspelled_word': 'jmps',
  'suggested_corrections': ['jumps'],
  'probabilities': [1.0]},
 {'misspelled_word': 'dgs',
  'suggested_corrections': ['dogs'],
  'probabilities': [1.0]}]

In [116]:
    
# Example usage
m = 2
k = 3
sentence = "The curius fox, while cautionly explring the dens and mysterius forest,\n" \
       "encuntered numrous challanges, including decptive trails and hiden obstacles,\n" \
       "yet perservered with remarkable determination, eventualy discovering a secludd haven\n" \
       "filled with facinating treasures and untaimed beuty."

vocab = {
    "the", "curious", "fox", "while", "cautiously", "exploring", "dense",
    "mysterious", "forest", "encountered", "numerous", "challenges",
    "including", "deceptive", "trails", "hidden", "obstacles", "yet",
    "persevered", "with", "remarkable", "determination", "eventually",
    "discovering", "secluded", "haven", "filled", "fascinating",
    "treasures", "untamed", "beauty", "and"
}


ngram_model = {
    'the': {
        'curious': 0.3, 'dense': 0.3, 'secluded': 0.4
    },
    'curious': {
        'fox': 1.0
    },
    'fox': {
        'while': 1.0
    },
    'while': {
        'cautiously': 1.0
    },
    'cautiously': {
        'exploring': 1.0
    },
    'exploring': {
        'the': 1.0
    },
    'dense': {
        'and': 1.0  # Added "and" to fit the sentence context
    },
    'and': {
        'mysterious': 0.5, 'hidden': 0.3, 'untamed': 0.2
    },
    'mysterious': {
        'forest': 1.0
    },
    'forest': {
        'encountered': 1.0
    },
    'encountered': {
        'numerous': 1.0
    },
    'numerous': {
        'challenges': 1.0
    },
    'challenges': {
        'including': 1.0
    },
    'including': {
        'deceptive': 0.6, 'hidden': 0.4
    },
    'deceptive': {
        'trails': 1.0
    },
    'hidden': {
        'obstacles': 1.0
    },
    'obstacles': {
        'yet': 1.0
    },
    'yet': {
        'persevered': 1.0
    },
    'persevered': {
        'with': 1.0
    },
    'with': {
        'remarkable': 1.0
    },
    'remarkable': {
        'determination': 1.0
    },
    'determination': {
        'eventually': 1.0
    },
    'eventually': {
        'discovering': 1.0
    },
    'discovering': {
        'a': 1.0
    },
    'a': {
        'secluded': 0.5, 'haven': 0.5
    },
    'secluded': {
        'haven': 1.0
    },
    'haven': {
        'filled': 1.0
    },
    'filled': {
        'with': 1.0
    },
    'fascinating': {
        'treasures': 1.0
    },
    'treasures': {
        'and': 1.0  # Added "and" to fit the sentence context
    },
    'untamed': {
        'beauty': 1.0
    }
}

ans = spelling_suggestions(sentence, vocab, m, ngram_model, k)
ans

[{'misspelled_word': 'curius',
  'suggested_corrections': ['curious'],
  'probabilities': [1.0]},
 {'misspelled_word': 'cautionly',
  'suggested_corrections': ['cautiously'],
  'probabilities': [1.0]},
 {'misspelled_word': 'explring',
  'suggested_corrections': ['exploring'],
  'probabilities': [1.0]},
 {'misspelled_word': 'dens',
  'suggested_corrections': ['dense'],
  'probabilities': [1.0]},
 {'misspelled_word': 'mysterius',
  'suggested_corrections': ['mysterious'],
  'probabilities': [1.0]},
 {'misspelled_word': 'encuntered',
  'suggested_corrections': ['encountered'],
  'probabilities': [1.0]},
 {'misspelled_word': 'numrous',
  'suggested_corrections': ['numerous'],
  'probabilities': [0]},
 {'misspelled_word': 'challanges',
  'suggested_corrections': ['challenges'],
  'probabilities': [1.0]},
 {'misspelled_word': 'decptive',
  'suggested_corrections': ['deceptive'],
  'probabilities': [1.0]},
 {'misspelled_word': 'hiden',
  'suggested_corrections': ['hidden', 'haven'],
  'probabilities': [1.0, 0.0]},
 {'misspelled_word': 'perservered',
  'suggested_corrections': ['persevered'],
  'probabilities': [1.0]},
 {'misspelled_word': 'eventualy',
  'suggested_corrections': ['eventually'],
  'probabilities': [1.0]},
 {'misspelled_word': 'a',
  'suggested_corrections': ['and'],
  'probabilities': [0]},
 {'misspelled_word': 'secludd',
  'suggested_corrections': ['secluded'],
  'probabilities': [1.0]},
 {'misspelled_word': 'facinating',
  'suggested_corrections': ['fascinating'],
  'probabilities': [1.0]},
 {'misspelled_word': 'untaimed',
  'suggested_corrections': ['untamed'],
  'probabilities': [1.0]},
 {'misspelled_word': 'beuty',
  'suggested_corrections': ['beauty'],
  'probabilities': [0]}]

In [117]:
t = ans[0].get("suggested_corrections")[0]
sentence = "The curius brwn fox jmps over the lazy dgs."
sentence = sentence.replace(sentence, t, 1)
sentence

'curious'

In [118]:
###############################################################
# TODO-10: Implement a function that selects the most likely  #
# correction of the misspelled words                          #
###############################################################

def spelling_corrector(sentence, vocab, m, ngram_model, k):
    """
    Corrects misspelled words in a given sentence by replacing them with the most likely corrections.

    Args:
        sentence (str): The input sentence containing misspelled words.
        vocab (set): The set of correct vocabulary words.
        m (int): The maximum edit distance for candidate generation.
        ngram_model (dict): The n-gram model for context evaluation.
        k (int): The number of top corrections to consider.

    Returns:
        str: The corrected sentence.
    """
    # Preprocess and identify misspelled words
    preprocessed_sentence = preprocess_text(sentence)
    misspelled_words = get_all_misspelled_words(preprocessed_sentence, vocab)

    for misspelled in misspelled_words:
        word = misspelled["word"]
        prev_word = misspelled["before"]
        next_word = misspelled["after"]

        # Get candidate corrections and rank them
        candidates = get_candidate_words(word, vocab, m)
        suggestions = get_top_k_corrections(prev_word, next_word, candidates, ngram_model, k)

        # Replace the word with the top suggestion
        if suggestions:
            top_correction = suggestions[0][0]  # First suggested correction
            sentence = sentence.replace(word, top_correction, 1)

    return sentence

    
# Example usage
m = 2
k = 3
sentence = "The quick brwn fox jmps over the lazy dgs. While the quick brwn dog screams"

vocab = {
    "the", "quick", "brown", "fox", "jumps", "over", "lazy", "dogs", "dog", "screams"
}

ngram_model = {
    'the': {
        'quick': 0.5, 'lazy': 0.5
    },
    'test': { 
        'brown': 0.75
    },
    'quick': {
        'brown': 1.0
    },
    'brown': {
        'fox': 0.75,
        'dog': 0.25
    },
    'fox': {
        'jumps': 1.0
    },
    'jumps': {
        'over': 1.0
    },
    'over': {
        'the': 1.0
    },
    'lazy': {
        'dogs': 1.0
    },
    'dog': {
        'screams': 1.0
    },
    'screams': {
        '.': 1.0
    }
}


ans = spelling_corrector(sentence, vocab, m, ngram_model, k) 
print(f"The original sentence was: \n{sentence}")
print(f"The new sentence is: \n{ans}")

############################################################
#                    End of your code.                     #
############################################################

The original sentence was:
The quick brwn fox jmps over the lazy dgs. While the quick brwn dog screams
The new sentence is:
The quick brown fox jumps over the lazy dogs. While the quick brown dog screams

In [119]:
sample_sentence_1 = "With news pshd to smart phnes in real time and sociaal media reactions spreading aross the glbe in seconds, the public dicussion can appear acelerated and temprally framented"

In [120]:
sample_sentence_2 = "tommato is a frit, not a vegtable"

In [121]:
sample_sentence_3 = "The quick brwn fox jumps oer the lay dog"

Now we want to test your spell checker.

In [122]:
# IMPORTANT NOTE: I MAKE THE ASSUMPTION THAT YOU HAVE A VALID VOCAB AND ALSO A VALID BIGRAM MODEL LIKE IN THE ORIGINAL DF

############################################################
# TODO-11: Print the result of your spelling suggestions   #
# function to the sample sentences above.                  #
############################################################
vocab = {
    "with", "news", "pushed", "to", "smart", "phones", "in", "real",
    "time", "and", "social", "media", "reactions", "spreading", 
    "across", "the", "globe", "seconds", "public", "discussion",
    "can", "appear", "accelerated", "temporally", "fragmented",
    "tomato", "is", "a", "fruit", "not", "vegetable", "quick",
    "brown", "fox", "jumps", "over", "lazy", "dog"
}

ngram_model = {
    "with": {"news": 1.0},
    "news": {"pushed": 1.0},
    "pushed": {"to": 1.0},
    "to": {"smart": 1.0},
    "smart": {"phones": 1.0},
    "phones": {"in": 1.0},
    "in": {"real": 0.5, "seconds": 0.5},
    "real": {"time": 1.0},
    "time": {"and": 1.0},
    "and": {"social": 0.5, "fragmented": 0.5},
    "social": {"media": 1.0},
    "media": {"reactions": 1.0},
    "reactions": {"spreading": 1.0},
    "spreading": {"across": 1.0},
    "across": {"the": 1.0},
    "the": {
        "globe": 0.2, "public": 0.2, "quick": 0.2, 
        "lazy": 0.2, "brown": 0.2  # Shared context across sentences
    },
    "globe": {"in": 1.0},
    "seconds": {"the": 1.0},
    "public": {"discussion": 1.0},
    "discussion": {"can": 1.0},
    "can": {"appear": 1.0},
    "appear": {"accelerated": 1.0},
    "accelerated": {"and": 1.0},
    "temporally": {"fragmented": 1.0},
    "fragmented": {".": 1.0},
    "tomato": {"is": 1.0},
    "is": {"a": 1.0},
    "a": {"fruit": 0.5, "vegetable": 0.5},
    "fruit": {"not": 1.0},
    "not": {"a": 1.0},
    "vegetable": {".": 1.0},
    "quick": {"brown": 1.0},
    "brown": {"fox": 1.0},
    "fox": {"jumps": 1.0},
    "jumps": {"over": 1.0},
    "over": {"the": 1.0},
    "lazy": {"dog": 1.0},
    "dog": {".": 1.0}
}

# Print the results of spelling suggestions
print("Spelling Suggestions for Sentence 1:")
print(spelling_suggestions(sample_sentence_1, vocab, m=2, ngram_model=ngram_model, k=3))

print("\nSpelling Suggestions for Sentence 2:")
print(spelling_suggestions(sample_sentence_2, vocab, m=2, ngram_model=ngram_model, k=3))

print("\nSpelling Suggestions for Sentence 3:")
print(spelling_suggestions(sample_sentence_3, vocab, m=2, ngram_model=ngram_model, k=3))
############################################################
#                    End of your code.                     #
############################################################

Spelling Suggestions for Sentence 1:
[{'misspelled_word': 'pshd', 'suggested_corrections': ['pushed'], 'probabilities': [1.0]}, {'misspelled_word': 'phnes', 'suggested_corrections': ['phones'], 'probabilities': [1.0]}, {'misspelled_word': 'sociaal', 'suggested_corrections': ['social'], 'probabilities': [1.0]}, {'misspelled_word': 'aross', 'suggested_corrections': ['across'], 'probabilities': [1.0]}, {'misspelled_word': 'glbe', 'suggested_corrections': ['globe'], 'probabilities': [1.0]}, {'misspelled_word': 'dicussion', 'suggested_corrections': ['discussion'], 'probabilities': [1.0]}, {'misspelled_word': 'acelerated', 'suggested_corrections': ['accelerated'], 'probabilities': [1.0]}, {'misspelled_word': 'temprally', 'suggested_corrections': ['temporally'], 'probabilities': [0]}, {'misspelled_word': 'framented', 'suggested_corrections': ['fragmented'], 'probabilities': [0]}]

Spelling Suggestions for Sentence 2:
[{'misspelled_word': 'tommato', 'suggested_corrections': ['tomato'], 'probabilities': [1.0]}, {'misspelled_word': 'frit', 'suggested_corrections': ['fruit'], 'probabilities': [1.0]}, {'misspelled_word': 'vegtable', 'suggested_corrections': ['vegetable'], 'probabilities': [1.0]}]

Spelling Suggestions for Sentence 3:
[{'misspelled_word': 'brwn', 'suggested_corrections': ['brown'], 'probabilities': [1.0]}, {'misspelled_word': 'oer', 'suggested_corrections': ['over'], 'probabilities': [1.0]}, {'misspelled_word': 'lay', 'suggested_corrections': ['lazy', 'can', 'a'], 'probabilities': [1.0, 0.0, 0.0]}]

In [123]:
############################################################
# TODO-12: Print the result of your spelling correction    #
# function to the sample sentences above.                  #
############################################################

# Correcting and printing results
corrected_sentence_1 = spelling_corrector(sample_sentence_1, vocab, m=2, ngram_model=ngram_model, k=3)
print(f"Original Sentence 1: {sample_sentence_1}")
print(f"Corrected Sentence 1: {corrected_sentence_1}")

corrected_sentence_2 = spelling_corrector(sample_sentence_2, vocab, m=2, ngram_model=ngram_model, k=3)
print(f"Original Sentence 2: {sample_sentence_2}")
print(f"Corrected Sentence 2: {corrected_sentence_2}")

corrected_sentence_3 = spelling_corrector(sample_sentence_3, vocab, m=2, ngram_model=ngram_model, k=3)
print(f"Original Sentence 3: {sample_sentence_3}")
print(f"Corrected Sentence 3: {corrected_sentence_3}")

############################################################
#                    End of your code.                     #
############################################################

Original Sentence 1: With news pshd to smart phnes in real time and sociaal media reactions spreading aross the glbe in seconds, the public dicussion can appear acelerated and temprally framented
Corrected Sentence 1: With news pushed to smart phones in real time and social media reactions spreading across the globe in seconds, the public discussion can appear accelerated and temporally fragmented
Original Sentence 2: tommato is a frit, not a vegtable
Corrected Sentence 2: tomato is a fruit, not a vegetable
Original Sentence 3: The quick brwn fox jumps oer the lay dog
Corrected Sentence 3: The quick brown fox jumps over the lazy dog

<span style='color:red'>**Question 01:**</span> What are the potential limitations / failure cases of this model? Give at least three and explain why for each.

<span style='color:red'>**A01:**</span> 
Contextual Ambiguity: The model relies on a 2-gram (bigram) context—specifically, it uses the word immediately before and after the misspelled token—to calculate probabilities for candidate corrections. This narrow window may not provide enough context to fully determine the intended meaning. For instance, if the sentence is complex or uses idiomatic expressions, the local context may be insufficient to correctly distinguish between homophones or similarly spelled words. Consequently, the model might suggest a correction that fits the local 2-gram statistics but is semantically inappropriate in the broader sentence. For example, if the word "bank" appears in a financial article versus a sentence about river geography, a simple bigram model might confuse the two meanings if the surrounding context isn’t strong enough to clarify the intent.

Limited Vocabulary: The model’s performance heavily depends on the predefined vocabulary set. If the vocabulary is not comprehensive—especially with regard to domain-specific or technical terms—it may incorrectly classify a correctly spelled, but uncommon, word as misspelled. This situation can lead to two issues: first, the model might attempt to “correct” words that are actually right, and second, it might provide corrections that do not belong to the relevant domain. For example, specialized medical or legal terms might be flagged as errors and replaced with more common words that are contextually incongruent, thus undermining the integrity of the text.

Reliance on Edit Distance: The model uses edit distance as a primary metric to generate candidate corrections. While edit distance is a useful measure for quantifying how similar two strings are, it does have limitations. It inherently favors words that require fewer character modifications, even if those words are contextually less appropriate. For instance, consider the misspelling "bannana." A candidate such as "banna" might have a smaller edit distance compared to "banana" because it involves fewer operations (like removing an extra character), yet "banana" is the semantically correct word. Moreover, edit distance alone does not capture phonetic similarity or consider word frequency—factors that are important in determining the likelihood of a candidate in real language use. This reliance can cause the model to suggest corrections that are close in form but not in meaning.

<span style='color:red'>**Question 02:**</span> Is there a benefit for having longer n-grams? Explain your answer.

<span style='color:red'>**A02:**</span> Consider the ambiguous word “bank.” With a bigram model, if we only capture the immediate pairings—such as "the bank" or "bank of"—the model might have difficulty determining whether “bank” refers to a financial institution or the side of a river. However, a trigram model can take into account a broader context. For example, in the sentence “I sat on the bank of the river,” the trigram “bank of the” combined with “of the river” provides a richer context that clearly indicates the intended meaning as a river bank. This example illustrates that longer n-grams can capture more contextual clues, leading to more accurate predictions or corrections. The trade-off, however, is that longer n-grams are prone to data sparsity and require larger datasets and more advanced smoothing techniques to function effectively.

<span style='color:red'>**Question 03:**</span> If we used a character level n-gram instead, what would be the advantages and disadvantages over the word level n-grams? Explain your answer.

<span style='color:red'>**A03:**</span>
Character-level n-grams work by breaking words down into sequences of individual characters, which makes them resilient to spelling errors and capable of capturing morphological variations. For example, consider the misspelled word "recieve" instead of "receive." A character-level model might note that both words share many similar subsequences like "rece" and "ive," enabling the model to recognize the intended word despite the error. This flexibility is particularly useful when the vocabulary is limited or when dealing with domain-specific terms.

On the other hand, because character-level models focus on small units, they often lose the semantic context that whole words provide. For instance, while character n-grams can capture that "cat" and "car" share many letters, they might struggle to differentiate meaning without explicit word boundaries. Additionally, operating at the character level results in longer sequences to process, which increases computational complexity and may lead to ambiguity. Thus, while character-level n-grams offer robustness in handling variations and errors, they may fall short in conveying overall semantic meaning compared to word-level models.

# Simplified Document Retrieval

TF-IDF (term frequency, inverse document frequency) is one of the simplest way you can retrieve relevant documents given a query. It can be seen as an extension of the bag of words model with the added benefit of weighting the words based on not only how often it appears but also how many documents use it. Intuitively, if the word is used in all documents, then it is not useful since it cannot discriminate between the documents.

Before we implement the TF-IDF document retrieval, let us first create the dataset that we will be working on. 

``paris_olympics_news_html.txt`` contains an html document that consists of several urls of articles from the Paris 2024 olympics.

In [124]:
with open("paris_olympics_news_html.txt","r", encoding="utf-8") as f:
    html = f.read()
html

'<ul data-cy="content-list-containter" class="content-list-grid"><li tabindex="0" data-cy="list-item" class="ContentListItem-styles__ListItem-sc-b482c069-0 jrbkWC latest-news content-list-grid-item"><article class="CardItem-styles__Wrapper-sc-407c96a5-20 jpcknG -type size-m CardItemWrapper-styles__CardItemHOC-sc-ebcfa57e-0 kvLaaK mosaic-layout content-inside" data-cy="card-m" data-tracking-payload="{&quot;link_tag&quot;:&quot;Paris 2024 Paralympics | They will give us chills: Gaëlle Edon&quot;,&quot;module&quot;:&quot;latest news&quot;,&quot;module_instance&quot;:&quot;Content List&quot;,&quot;module_position&quot;:1,&quot;destination_url&quot;:&quot;https://olympics.com/en/news/paris-2024-paralympics-they-will-give-us-chills-gaelle-edon&quot;,&quot;content_id&quot;:&quot;af8fc23c-968e-41c9-b392-bb12cb7821e7&quot;,&quot;translation_id&quot;:&quot;ceea7e71-fa27-4e62-af24-b65678070658&quot;}"><div data-cy="image-tag-container" class="CardItem-styles__ImageAndTagWrapper-sc-407c96a5-0 clgxMC image-tag-container"><a data-cy="link" class="CardItem-styles__ImageWrapper-sc-407c96a5-1 llTdl card-item-image-wrapper" href="https://olympics.com/en/news/paris-2024-paralympics-they-will-give-us-chills-gaelle-edon" target="_self" data-tracking-payload="{&quot;link_tag&quot;:&quot;Paris 2024 Paralympics | They will give us chills: Gaëlle Edon&quot;,&quot;module&quot;:&quot;latest news&quot;,&quot;module_instance&quot;:&quot;Content List&quot;,&quot;module_position&quot;:1,&quot;destination_url&quot;:&quot;https://olympics.com/en/news/paris-2024-paralympics-they-will-give-us-chills-gaelle-edon&quot;,&quot;content_id&quot;:&quot;af8fc23c-968e-41c9-b392-bb12cb7821e7&quot;,&quot;translation_id&quot;:&quot;ceea7e71-fa27-4e62-af24-b65678070658&quot;}"><picture data-cy="picture-wrapper" class="styles__Picture-sc-3cfb7849-0 eeYsQp"><source media="(max-width: 374px)" srcset="https://img.olympics.com/images/image/private/t_16-9_640/f_auto/primary/id8jtiyuxuw9snmy8580, https://img.olympics.com/images/image/private/t_16-9_640/f_auto/primary/id8jtiyuxuw9snmy8580 2x"><img alt="Paris 2024 Paralympics | They will give us chills: Gaëlle Edon" src="https://img.olympics.com/images/image/private/t_16-9_640/f_auto/primary/id8jtiyuxuw9snmy8580"></picture></a><div data-cy="tag-and-type" class="CardItem-styles__ImageTagAndType-sc-407c96a5-2 cxWSsQ tag-and-type"></div></div><div class="CardItem-styles__TextWrapperContainer-sc-407c96a5-10 fkQvLN text-wrapper-container"><article class="CardItem-styles__TextWrapper-sc-407c96a5-14 dtPXfY text-container  " data-cy="text-container"><div><div class="CardItem-styles__PrimaryTagWrapper-sc-407c96a5-21 jPMojc tags"><a data-cy="primary-tag" class="CardItem-styles__PrimaryTag-sc-407c96a5-17 khbAfd primary-tag" data-tracking-payload="{&quot;link_tag&quot;:&quot;Paris 2024 Paralympics | They will give us chills: Gaëlle Edon&quot;,&quot;module&quot;:&quot;latest news&quot;,&quot;module_instance&quot;:&quot;Content List&quot;,&quot;module_position&quot;:1,&quot;destination_url&quot;:&quot;https://olympics.com/en/news/paris-2024-paralympics-they-will-give-us-chills-gaelle-edon&quot;,&quot;content_id&quot;:&quot;af8fc23c-968e-41c9-b392-bb12cb7821e7&quot;,&quot;translation_id&quot;:&quot;ceea7e71-fa27-4e62-af24-b65678070658&quot;}" href="https://olympics.com/en/paris-2024/paralympic-games/sports/shooting-para-sport"><span class="sc-bdnyFh iRoa-dR text--tag">Shooting Para Sport</span></a></div><a data-cy="link" class="" href="https://olympics.com/en/news/paris-2024-paralympics-they-will-give-us-chills-gaelle-edon" target="_self" data-tracking-payload="{&quot;link_tag&quot;:&quot;Paris 2024 Paralympics | They will give us chills: Gaëlle Edon&quot;,&quot;module&quot;:&quot;latest news&quot;,&quot;module_instance&quot;:&quot;Content List&quot;,&quot;module_position&quot;:1,&quot;destination_url&quot;:&quot;https://olympics.com/en/news/paris-2024-paralympics-they-will-give-us-chills-gaelle-edon&quot;,&quot;content_id&quot;:&quot;af8fc23c-968e-41c9-b392-bb12cb7821e7&quot;,&quot;translation_id&quot;:&quot;ceea7e71-fa27-4e62-af24-b65678070658&quot;}"><div class="CardItem-styles__Title-sc-407c96a5-3 kyLNoV card-title-wrapper" data-cy="title"><h3 data-cy="title" class="sc-bdnyFh iUjvAZ card-title  text--xs-title">Paris 2024 Paralympics | They will give us chills: Gaëlle Edon</h3></div></a></div></article></div></article></li><li tabindex="0" data-cy="list-item" class="ContentListItem-styles__ListItem-sc-b482c069-0 jrbkWC latest-news content-list-grid-item"><article class="CardItem-styles__Wrapper-sc-407c96a5-20 jpcknG -type size-m CardItemWrapper-styles__CardItemHOC-sc-ebcfa57e-0 kvLaaK mosaic-layout content-inside" data-cy="card-m" data-tracking-payload="{&quot;link_tag&quot;:&quot;Letsile Tebogo: The new face of Africa\'s sprinting revolution&quot;,&quot;module&quot;:&quot;latest news&quot;,&quot;module_instance&quot;:&quot;Content List&quot;,&quot;module_position&quot;:2,&quot;destination_url&quot;:&quot;https://olympics.com/en/news/letsile-tebogo-africa-sprinting-revolution&quot;,&quot;content_id&quot;:&quot;49f9675d-62c5-47c0-aa50-6d76aa119f17&quot;,&quot;translation_id&quot;:&quot;48ce723e-12e3-4005-9753-9d34462c757a&quot;}"><div data-cy="image-tag-container" class="CardItem-styles__ImageAndTagWrapper-sc-407c96a5-0 clgxMC image-tag-container"><a data-cy="link" class="CardItem-styles__ImageWrapper-sc-407c96a5-1 llTdl card-item-image-wrapper" href="https://olympics.com/en/news/letsile-tebogo-africa-sprinting-revolution" target="_self" data-tracking-payload="{&quot;link_tag&quot;:&quot;Letsile Tebogo: The new face of Africa\'s sprinting revolution&quot;,&quot;module&quot;:&quot;latest news&quot;,&quot;module_instance&quot;:&quot;Content List&quot;,&quot;module_position&quot;:2,&quot;destination_url&quot;:&quot;https://olympics.com/en/news/letsile-tebogo-africa-sprinting-revolution&quot;,&quot;content_id&quot;:&quot;49f9675d-62c5-47c0-aa50-6d76aa119f17&quot;,&quot;translation_id&quot;:&quot;48ce723e-12e3-4005-9753-9d34462c757a&quot;}"><picture data-cy="picture-wrapper" class="styles__Picture-sc-3cfb7849-0 eeYsQp"><source media="(max-width: 374px)" srcset="https://img.olympics.com/images/image/private/t_16-9_640/f_auto/primary/z7kq3x1eqc4io2vwy7i8, https://img.olympics.com/images/image/private/t_16-9_640/f_auto/primary/z7kq3x1eqc4io2vwy7i8 2x"><img alt="Letsile Tebogo: The new face of Africa\'s sprinting revolution" src="https://img.olympics.com/images/image/private/t_16-9_640/f_auto/primary/z7kq3x1eqc4io2vwy7i8"></picture></a><div data-cy="tag-and-type" class="CardItem-styles__ImageTagAndType-sc-407c96a5-2 cxWSsQ tag-and-type"></div></div><div class="CardItem-styles__TextWrapperContainer-sc-407c96a5-10 fkQvLN text-wrapper-container"><article class="CardItem-styles__TextWrapper-sc-407c96a5-14 dtPXfY text-container  " data-cy="text-container"><div><div class="CardItem-styles__PrimaryTagWrapper-sc-407c96a5-21 jPMojc tags"><a data-cy="primary-tag" class="CardItem-styles__PrimaryTag-sc-407c96a5-17 khbAfd primary-tag" data-tracking-payload="{&quot;link_tag&quot;:&quot;Letsile Tebogo: The new face of Africa\'s sprinting revolution&quot;,&quot;module&quot;:&quot;latest news&quot;,&quot;module_instance&quot;:&quot;Content List&quot;,&quot;module_position&quot;:2,&quot;destination_url&quot;:&quot;https://olympics.com/en/news/letsile-tebogo-africa-sprinting-revolution&quot;,&quot;content_id&quot;:&quot;49f9675d-62c5-47c0-aa50-6d76aa119f17&quot;,&quot;translation_id&quot;:&quot;48ce723e-12e3-4005-9753-9d34462c757a&quot;}" href="https://olympics.com/en/athletes/letsile-tebogo"><span class="sc-bdnyFh iRoa-dR text--tag">Letsile TEBOGO</span></a></div><a data-cy="link" class="" href="https://olympics.com/en/news/letsile-tebogo-africa-sprinting-revolution" target="_self" data-tracking-payload="{&quot;link_tag&quot;:&quot;Letsile Tebogo: The new face of Africa\'s sprinting revolution&quot;,&quot;module&quot;:&quot;latest news&quot;,&quot;module_instance&quot;:&quot;Content List&quot;,&quot;module_position&quot;:2,&quot;destination_url&quot;:&quot;https://olympics.com/en/news/letsile-tebogo-africa-sprinting-revolution&quot;,&quot;content_id&quot;:&quot;49f9675d-62c5-47c0-aa50-6d76aa119f17&quot;,&quot;translation_id&quot;:&quot;48ce723e-12e3-4005-9753-9d34462c757a&quot;}"><div class="CardItem-styles__Title-sc-407c96a5-3 kyLNoV card-title-wrapper" data-cy="title"><h3 data-cy="title" class="sc-bdnyFh iUjvAZ card-title  text--xs-title">Letsile Tebogo: The new face of Africa\'s sprinting revolution</h3></div></a></div></article></div></article></li><li tabindex="0" data-cy="list-item" class="ContentListItem-styles__ListItem-sc-b482c069-0 jrbkWC latest-news content-list-grid-item"><article class="CardItem-styles__Wrapper-sc-407c96a5-20 jpcknG -type size-m CardItemWrapper-styles__CardItemHOC-sc-ebcfa57e-0 kvLaaK mosaic-layout content-inside" data-cy="card-m" data-tracking-payload="{&quot;link_tag&quot;:&quot;How Paris 2024 was Noah Lyles’ greatest triumph and hardest challenge&quot;,&quot;module&quot;:&quot;latest news&quot;,&quot;module_instance&quot;:&quot;Content List&quot;,&quot;module_position&quot;:3,&quot;destination_url&quot;:&quot;https://olympics.com/en/news/paris-2024-noah-lyles-greatest-triumph-hardest-challenge&quot;,&quot;content_id&quot;:&quot;0d154a97-fa74-4e59-83e0-7cac7ce56826&quot;,&quot;translation_id&quot;:&quot;e672e061-08b8-47a4-bebe-d41842ed2ddd&quot;}"><div data-cy="image-tag-container" class="CardItem-styles__ImageAndTagWrapper-sc-407c96a5-0 clgxMC image-tag-container"><a data-cy="link" class="CardItem-styles__ImageWrapper-sc-407c96a5-1 llTdl card-item-image-wrapper" href="https://olympics.com/en/news/paris-2024-noah-lyles-greatest-triumph-hardest-challenge" target="_self" data-tracking-payload="{&quot;link_tag&quot;:&quot;How Paris 2024 was Noah Lyles’ greatest triumph and hardest challenge&quot;,&quot;module&quot;:&quot;latest news&quot;,&quot;module_instance&quot;:&quot;Content List&quot;,&quot;module_position&quot;:3,&quot;destination_url&quot;:&quot;https://olympics.com/en/news/paris-2024-noah-lyles-greatest-triumph-hardest-challenge&quot;,&quot;content_id&quot;:&quot;0d154a97-fa74-4e59-83e0-7cac7ce56826&quot;,&quot;translation_id&quot;:&quot;e672e061-08b8-47a4-bebe-d41842ed2ddd&quot;}"><picture data-cy="picture-wrapper" class="styles__Picture-sc-3cfb7849-0 eeYsQp"><source media="(max-width: 374px)" srcset="https://img.olympics.com/images/image/private/t_16-9_640/f_auto/primary/cel9ljqjpacezg5h2scq, https://img.olympics.com/images/image/private/t_16-9_640/f_auto/primary/cel9ljqjpacezg5h2scq 2x"><img alt="How Paris 2024 was Noah Lyles’ greatest triumph and hardest challenge" src="https://img.olympics.com/images/image/private/t_16-9_640/f_auto/primary/cel9ljqjpacezg5h2scq"></picture></a><div data-cy="tag-and-type" class="CardItem-styles__ImageTagAndType-sc-407c96a5-2 cxWSsQ tag-and-type"></div></div><div class="CardItem-styles__TextWrapperContainer-sc-407c96a5-10 fkQvLN text-wrapper-container"><article class="CardItem-styles__TextWrapper-sc-407c96a5-14 dtPXfY text-container  " data-cy="text-container"><div><div class="CardItem-styles__PrimaryTagWrapper-sc-407c96a5-21 jPMojc tags"><a data-cy="primary-tag" class="CardItem-styles__PrimaryTag-sc-407c96a5-17 khbAfd primary-tag" data-tracking-payload="{&quot;link_tag&quot;:&quot;How Paris 2024 was Noah Lyles’ greatest triumph and hardest challenge&quot;,&quot;module&quot;:&quot;latest news&quot;,&quot;module_instance&quot;:&quot;Content List&quot;,&quot;module_position&quot;:3,&quot;destination_url&quot;:&quot;https://olympics.com/en/news/paris-2024-noah-lyles-greatest-triumph-hardest-challenge&quot;,&quot;content_id&quot;:&quot;0d154a97-fa74-4e59-83e0-7cac7ce56826&quot;,&quot;translation_id&quot;:&quot;e672e061-08b8-47a4-bebe-d41842ed2ddd&quot;}" href="https://olympics.com/en/athletes/noah-lyles"><span class="sc-bdnyFh iRoa-dR text--tag">Noah LYLES</span></a></div><a data-cy="link" class="" href="https://olympics.com/en/news/paris-2024-noah-lyles-greatest-triumph-hardest-challenge" target="_self" data-tracking-payload="{&quot;link_tag&quot;:&quot;How Paris 2024 was Noah Lyles’ greatest triumph and hardest challenge&quot;,&quot;module&quot;:&quot;latest news&quot;,&quot;module_instance&quot;:&quot;Content List&quot;,&quot;module_position&quot;:3,&quot;destination_url&quot;:&quot;https://olympics.com/en/news/paris-2024-noah-lyles-greatest-triumph-hardest-challenge&quot;,&quot;content_id&quot;:&quot;0d154a97-fa74-4e59-83e0-7cac7ce56826&quot;,&quot;translation_id&quot;:&quot;e672e061-08b8-47a4-bebe-d41842ed2ddd&quot;}"><div class="CardItem-styles__Title-sc-407c96a5-3 kyLNoV card-title-wrapper" data-cy="title"><h3 data-cy="title" class="sc-bdnyFh iUjvAZ card-title  text--xs-title">How Paris 2024 was Noah Lyles’ greatest triumph and hardest challenge</h3></div></a></div></article></div></article></li><li tabindex="0" data-cy="list-item" class="ContentListItem-styles__ListItem-sc-b482c069-0 jrbkWC latest-news content-list-grid-item"><article class="CardItem-styles__Wrapper-sc-407c96a5-20 jpcknG -type size-m CardItemWrapper-styles__CardItemHOC-sc-ebcfa57e-0 kvLaaK mosaic-layout content-inside" data-cy="card-m" data-tracking-payload="{&quot;link_tag&quot;:&quot;Kaylia Nemour looks back on Paris 2024 and ahead to LA28 in an exclusive interview&quot;,&quot;module&quot;:&quot;latest news&quot;,&quot;module_instance&quot;:&quot;Content List&quot;,&quot;module_position&quot;:4,&quot;destination_url&quot;:&quot;https://olympics.com/en/news/paris-2024-artistic-gymnastics-kaylia-nemour-exclusive-interview&quot;,&quot;content_id&quot;:&quot;fc6de2b1-afe1-4804-aa66-16c5f3ca9f0c&quot;,&quot;translation_id&quot;:&quot;a6841083-896e-4c21-8045-73297c4c364e&quot;}"><div data-cy="image-tag-container" class="CardItem-styles__ImageAndTagWrapper-sc-407c96a5-0 clgxMC image-tag-container"><a data-cy="link" class="CardItem-styles__ImageWrapper-sc-407c96a5-1 llTdl card-item-image-wrapper" href="https://olympics.com/en/news/paris-2024-artistic-gymnastics-kaylia-nemour-exclusive-interview" target="_self" data-tracking-payload="{&quot;link_tag&quot;:&quot;Kaylia Nemour looks back on Paris 2024 and ahead to LA28 in an exclusive interview&quot;,&quot;module&quot;:&quot;latest news&quot;,&quot;module_instance&quot;:&quot;Content List&quot;,&quot;module_position&quot;:4,&quot;destination_url&quot;:&quot;https://olympics.com/en/news/paris-2024-artistic-gymnastics-kaylia-nemour-exclusive-interview&quot;,&quot;content_id&quot;:&quot;fc6de2b1-afe1-4804-aa66-16c5f3ca9f0c&quot;,&quot;translation_id&quot;:&quot;a6841083-896e-4c21-8045-73297c4c364e&quot;}"><picture data-cy="picture-wrapper" class="styles__Picture-sc-3cfb7849-0 eeYsQp"><source media="(max-width: 374px)" srcset="https://img.olympics.com/images/image/private/t_16-9_640/f_auto/primary/hkfh73u45i4tp6dovxep, https://img.olympics.com/images/image/private/t_16-9_640/f_auto/primary/hkfh73u45i4tp6dovxep 2x"><img alt="Kaylia Nemour looks back on Paris 2024 and ahead to LA28 in an exclusive interview" src="https://img.olympics.com/images/image/private/t_16-9_640/f_auto/primary/hkfh73u45i4tp6dovxep"></picture></a><div data-cy="tag-and-type" class="CardItem-styles__ImageTagAndType-sc-407c96a5-2 cxWSsQ tag-and-type"></div></div><div class="CardItem-styles__TextWrapperContainer-sc-407c96a5-10 fkQvLN text-wrapper-container"><article class="CardItem-styles__TextWrapper-sc-407c96a5-14 dtPXfY text-container  " data-cy="text-container"><div><div class="CardItem-styles__PrimaryTagWrapper-sc-407c96a5-21 jPMojc tags"><a data-cy="primary-tag" class="CardItem-styles__PrimaryTag-sc-407c96a5-17 khbAfd primary-tag" data-tracking-payload="{&quot;link_tag&quot;:&quot;Kaylia Nemour looks back on Paris 2024 and ahead to LA28 in an exclusive interview&quot;,&quot;module&quot;:&quot;latest news&quot;,&quot;module_instance&quot;:&quot;Content List&quot;,&quot;module_position&quot;:4,&quot;destination_url&quot;:&quot;https://olympics.com/en/news/paris-2024-artistic-gymnastics-kaylia-nemour-exclusive-interview&quot;,&quot;content_id&quot;:&quot;fc6de2b1-afe1-4804-aa66-16c5f3ca9f0c&quot;,&quot;translation_id&quot;:&quot;a6841083-896e-4c21-8045-73297c4c364e&quot;}" href="https://olympics.com/en/athletes/kaylia-nemour"><span class="sc-bdnyFh iRoa-dR text--tag">Kaylia NEMOUR</span></a></div><a data-cy="link" class="" href="https://olympics.com/en/news/paris-2024-artistic-gymnastics-kaylia-nemour-exclusive-interview" target="_self" data-tracking-payload="{&quot;link_tag&quot;:&quot;Kaylia Nemour looks back on Paris 2024 and ahead to LA28 in an exclusive interview&quot;,&quot;module&quot;:&quot;latest news&quot;,&quot;module_instance&quot;:&quot;Content List&quot;,&quot;module_position&quot;:4,&quot;destination_url&quot;:&quot;https://olympics.com/en/news/paris-2024-artistic-gymnastics-kaylia-nemour-exclusive-interview&quot;,&quot;content_id&quot;:&quot;fc6de2b1-afe1-4804-aa66-16c5f3ca9f0c&quot;,&quot;translation_id&quot;:&quot;a6841083-896e-4c21-8045-73297c4c364e&quot;}"><div class="CardItem-styles__Title-sc-407c96a5-3 kyLNoV card-title-wrapper" data-cy="title"><h3 data-cy="title" class="sc-bdnyFh iUjvAZ card-title  text--xs-title">Kaylia Nemour looks back on Paris 2024 and ahead to LA28 in an exclusive interview</h3></div></a></div></article></div></article></li><li tabindex="0" data-cy="list-item" class="ContentListItem-styles__ListItem-sc-b482c069-0 jrbkWC latest-news content-list-grid-item"><article class="CardItem-styles__Wrapper-sc-407c96a5-20 jpcknG -type size-m CardItemWrapper-styles__CardItemHOC-sc-ebcfa57e-0 kvLaaK mosaic-layout content-inside" data-cy="card-m" data-tracking-payload="{&quot;link_tag&quot;:&quot;Stronger post-injury, Sky Brown set on gold in two sports at LA28&quot;,&quot;module&quot;:&quot;latest news&quot;,&quot;module_instance&quot;:&quot;Content List&quot;,&quot;module_position&quot;:5,&quot;destination_url&quot;:&quot;https://olympics.com/en/news/sky-brown-gender-gap-la28-targets-exclusive&quot;,&quot;content_id&quot;:&quot;8d373662-2e22-4928-a33a-da6516763704&quot;,&quot;translation_id&quot;:&quot;c1d1d037-0e3d-4bf0-8bc7-62d10136f1ad&quot;}"><div data-cy="image-tag-container" class="CardItem-styles__ImageAndTagWrapper-sc-407c96a5-0 clgxMC image-tag-container"><a data-cy="link" class="CardItem-styles__ImageWrapper-sc-407c96a5-1 llTdl card-item-image-wrapper" href="https://olympics.com/en/news/sky-brown-gender-gap-la28-targets-exclusive" target="_self" data-tracking-payload="{&quot;link_tag&quot;:&quot;Stronger post-injury, Sky Brown set on gold in two sports at LA28&quot;,&quot;module&quot;:&quot;latest news&quot;,&quot;module_instance&quot;:&quot;Content List&quot;,&quot;module_position&quot;:5,&quot;destination_url&quot;:&quot;https://olympics.com/en/news/sky-brown-gender-gap-la28-targets-exclusive&quot;,&quot;content_id&quot;:&quot;8d373662-2e22-4928-a33a-da6516763704&quot;,&quot;translation_id&quot;:&quot;c1d1d037-0e3d-4bf0-8bc7-62d10136f1ad&quot;}"><picture data-cy="picture-wrapper" class="styles__Picture-sc-3cfb7849-0 eeYsQp"><source media="(max-width: 374px)" srcset="https://img.olympics.com/images/image/private/t_16-9_640/f_auto/primary/quhxx1ndqyndwafyvnyv, https://img.olympics.com/images/image/private/t_16-9_640/f_auto/primary/quhxx1ndqyndwafyvnyv 2x"><img alt="Stronger post-injury, Sky Brown set on gold in two sports at LA28" src="https://img.olympics.com/images/image/private/t_16-9_640/f_auto/primary/quhxx1ndqyndwafyvnyv"></picture></a><div data-cy="tag-and-type" class="CardItem-styles__ImageTagAndType-sc-407c96a5-2 cxWSsQ tag-and-type"></div></div><div class="CardItem-styles__TextWrapperContainer-sc-407c96a5-10 fkQvLN text-wrapper-container"><article class="CardItem-styles__TextWrapper-sc-407c96a5-14 dtPXfY text-container  " data-cy="text-container"><div><div class="CardItem-styles__PrimaryTagWrapper-sc-407c96a5-21 jPMojc tags"><a data-cy="primary-tag" class="CardItem-styles__PrimaryTag-sc-407c96a5-17 khbAfd primary-tag" data-tracking-payload="{&quot;link_tag&q

As you can see in the wall of text above, it is not in a very easy to get format.
Fortunately, we can use regex to extract all the urls want.

Look at this link to learn how to use regex in python <br />
Link: https://www.w3schools.com/python/python_regex.asp

In [125]:
############################################################
# TODO-13: Write code to extract all the urls from the html#
# text using regex (regular expressions). See the tutorial #
# link above.                                              #
############################################################

# Regular expression pattern to match URLs
url_pattern = r'https?://[^\s"]+'

all_links = re.findall(url_pattern, html)


############################################################
#                    End of your code.                     #
############################################################

print(all_links[50])
print(f"The amount of urls is: {len(all_links)}")

https://olympics.com/en/news/kristen-faulkner-venture-capitalism-better-cyclist&quot;,&quot;content_id&quot;:&quot;21fb4c82-dad1-4481-ba1d-5fded9724fc9&quot;,&quot;translation_id&quot;:&quot;cf027b3e-0bb0-4d38-9ffe-abe4efb2edbd&quot;}
The amount of urls is: 15344

You will see that the links also contain links to images. We only want the links to articles so we have to modify the regex to only get the article links and not the image links.

In [126]:
###############################################################
# TODO-14: Modify the regex to capture only the article links #
# and not the image links. There might also be duplicate      #
# links, so make sure to remove the duplicates.               #
###############################################################
import re

# Open and read the HTML file
with open("paris_olympics_news_html.txt", "r", encoding="utf-8") as f:
    html = f.read()

# Step 1: Extract all URLs from the HTML.
url_pattern = r'https?://[^\s"]+'
all_links = re.findall(url_pattern, html)

# Step 2: Filter to keep only article links.
# Exclude URLs that:
#   1. End with common image file extensions.
#   2. Contain the domain 'img.olympics.com'
filtered_links = [
    link for link in all_links 
    if not re.search(r'\.(?:jpg|jpeg|png|gif|svg)(?:\?.*)?$', link, re.IGNORECASE)
    and "img.olympics.com" not in link
]

# Remove duplicates by converting the list to a set, then back to a list.
unique_links = list(set(filtered_links))

###############################################################
#                    End of your code.                        #
###############################################################

print(unique_links)
print(f"The amount of urls is: {len(unique_links)}")

['https://olympics.com/en/news/paris-2024-olympics-fencers-manon-apithy-brunet-sara-balzer-celebrates-club-france&quot;,&quot;content_id&quot;:&quot;5375d472-7428-4b30-9403-68f099c9eda5&quot;,&quot;translation_id&quot;:&quot;f4d6b92b-250c-42ea-9a96-727ded5f7986&quot;}', 'https://olympics.com/en/news/katie-ledecky-reveals-secret-longevity-swimming&quot;,&quot;content_id&quot;:&quot;2362d088-ce20-4242-961d-2e2d87e2ffe3&quot;,&quot;translation_id&quot;:&quot;fdc6b4f4-985a-4fdb-9e28-e2cb556765c7&quot;}', 'https://olympics.com/en/news/paris-2024-olympics-swimming-australia-results-times-medal-winners', 'https://olympics.com/en/news/paris-2024-olympics-judo-all-results-as-japan-s-nagase-takanori-captures-his-second-consecutive-gold-medal-in-men-s-81kg', 'https://olympics.com/en/news/usa-basketball-star-diana-taurasi-says-paris-2024-are-her-final-olympic-games&quot;,&quot;content_id&quot;:&quot;84da49b3-8f72-43d2-a897-21ac3bb983c5&quot;,&quot;translation_id&quot;:&quot;1a45c61f-48c5-4ec3-a485-7e1e317c7afb&quot;}', 'https://olympics.com/en/news/jeux-olympiques-paris-2024-conclure-en-beaute', 'https://olympics.com/en/news/paris-2024-olympics-rugby-sevens-schedule-australia&quot;,&quot;content_id&quot;:&quot;85fada01-d651-4f11-8bd9-b2d3ffda6044&quot;,&quot;translation_id&quot;:&quot;5f1ebf86-a468-4ca2-bcc7-7f81efe66e9b&quot;}', 'https://olympics.com/en/athletes/darja-varfolomeev', 'https://olympics.com/en/news/paris-2024-basketball-derrick-white-surprise-call-usa', 'https://olympics.com/en/news/paris-2024-olympics-vinesh-phogat-wrestling-schedule-women-50kg', 'https://olympics.com/en/news/ashwini-ponnappa-indian-badminton-last-olympics-paris-2024&quot;,&quot;content_id&quot;:&quot;6b0302fb-efa2-4d7a-9628-dbbb0720e64f&quot;,&quot;translation_id&quot;:&quot;378ba37b-1694-4bc0-83ce-df9528699c1a&quot;}', 'https://olympics.com/en/news/paris-2024-olympics-australia-road-cycling-lucas-plapp-injury-replacement', 'https://olympics.com/en/news/paris-2024-fencing-hong-kong-china-cheung-ka-long-olympic-champion-mens-foil-individual&quot;,&quot;content_id&quot;:&quot;3f83ee99-6aff-4da6-a18e-e6c5cfe12530&quot;,&quot;translation_id&quot;:&quot;c09b61de-30ba-44b1-931d-83244d0f3363&quot;}', 'https://olympics.com/en/news/im-aeji-takes-womens-54kg-bronze-boxing-paris-2024', 'https://olympics.com/en/news/skateboarding-women-park-preview-full-schedule-and-how-to-watch-live', 'https://olympics.com/en/news/keely-hodgkinson-olympic-gold-future-keys-to-success', 'https://olympics.com/en/news/paris-2024-olympics-why-you-dont-want-to-miss-triathlon&quot;,&quot;content_id&quot;:&quot;5cb09ac9-0a2f-40cc-8fac-ab1da6a5d492&quot;,&quot;translation_id&quot;:&quot;d1992ddd-9910-4f21-b086-29e60ca5cc27&quot;}', 'https://olympics.com/en/news/paris-2024-men-volleyball-semi-finals&quot;,&quot;content_id&quot;:&quot;9d00046a-1bd4-4a12-bcd8-bf95313ace87&quot;,&quot;translation_id&quot;:&quot;dd8344ab-8cc5-48d0-b0ba-a94d58e1f95c&quot;}', 'https://olympics.com/en/news/paris-2024-olympics-table-tennis-india-vs-china-round-of-16-results&quot;,&quot;content_id&quot;:&quot;670b9673-e220-438b-8250-1259d59cab42&quot;,&quot;translation_id&quot;:&quot;00dadb4d-969c-436d-9f25-32282d026a4d&quot;}', 'https://olympics.com/en/news/paris-2024-olympics-australia-vs-usa-hockey-women-group-match-3', 'https://olympics.com/en/news/paris-2024-skateboard-street-men-horigome-eaton-huston', 'https://olympics.com/en/news/paris-2024-olympics-pv-sindhu-badminton-schedule-women-singles', 'https://olympics.com/en/news/paris-2024-badminton-women-doubles-results&quot;,&quot;content_id&quot;:&quot;a5dd1e0d-dac1-448a-a885-9d6be22d202e&quot;,&quot;translation_id&quot;:&quot;9a2ef505-a461-4011-9114-a6b2907935e8&quot;}', 'https://olympics.com/en/news/paris-2024-olympics-badminton-india-pv-sindhu-lakshya-sen-hs-prannoy-group&quot;,&quot;content_id&quot;:&quot;0b57a165-7294-4153-8e41-d537c350dc22&quot;,&quot;translation_id&quot;:&quot;39369629-addb-4a32-ae7c-bf45bcd39afb&quot;}', 'https://olympics.com/en/news/teen-history-maker-arisa-trew-australia-exclusive-whirldwind-paris-ulympics-medal', 'https://olympics.com/en/news/paris-2024-basketball-men-wembanyama-france-japan&quot;,&quot;content_id&quot;:&quot;25e6a134-eac8-4b1d-b6f8-aaeb6dd494e7&quot;,&quot;translation_id&quot;:&quot;d0c25717-3320-4158-9ee4-3507a2a853d1&quot;}', 'https://olympics.com/en/paris-2024/sports/cycling-mountain-bike', 'https://olympics.com/en/news/paris-2024-olympics-archery-india-women-team-quarter-finals-results', 'https://olympics.com/en/news/paris-2024-olympics-women-basketball-australia-vs-serbia-quarter-finals-live-time', 'https://olympics.com/en/news/paris-2024-olympics-full-list-ioc-national-olympic-committee-codes&quot;,&quot;content_id&quot;:&quot;fe35176b-c5b8-438c-82de-a98770119fd0&quot;,&quot;translation_id&quot;:&quot;c0c256ba-5e25-4c98-a454-b1072e0c00d1&quot;}', 'https://olympics.com/en/paris-2024/sports/judo', 'https://olympics.com/en/news/paris-2024-great-britain-preview-athletes-7-august', 'https://olympics.com/en/news/akani-simbine-narrowly-misses-podium-in-third-consecutive-olympic-100m-final', 'https://olympics.com/en/news/paris-2024-olympics-michelle-jenneke-athletics-100m-hurdles-schedule', 'https://olympics.com/en/news/paris-2024-olympic-paralympic-games-why-track-purple-stade-de-france&quot;,&quot;content_id&quot;:&quot;96ab8b55-38e8-4255-a643-92643b178990&quot;,&quot;translation_id&quot;:&quot;b62e8d03-7c54-4216-8bb5-d89386b8b69c&quot;}', 'https://olympics.com/en/news/paris-2024-olympics-hockey-netherlands-vs-australia-quarter-finals-live-time&quot;,&quot;content_id&quot;:&quot;5d6faa55-b147-4f3f-b49d-a9252afbfe19&quot;,&quot;translation_id&quot;:&quot;863b26e6-319e-4c80-a2e0-3b1a493d59b2&quot;}', 'https://olympics.com/en/news/paris-2024-sailing-all-results-italy-sail-to-mixed-multihull-olympic-gold&quot;,&quot;content_id&quot;:&quot;d8eb122b-7078-4aa7-82d4-b29ae41ebf42&quot;,&quot;translation_id&quot;:&quot;1cf5c202-efad-40d9-8cb3-6486242afe0c&quot;}', 'https://olympics.com/en/news/jade-carey-s-happy-end-in-paris-bronze-olympics-vault&quot;,&quot;content_id&quot;:&quot;9afb38b6-f787-48d8-9020-e840685ae6bb&quot;,&quot;translation_id&quot;:&quot;e68e75d0-8259-4053-959b-8aa79f408911&quot;}', 'https://olympics.com/en/news/paris-2024-athletics-team-gb-keely-hodgkinson-charges-to-victory-womens-800m-final', 'https://olympics.com/en/news/paris-2024-basketball-women-usa-win-belgium&quot;,&quot;content_id&quot;:&quot;dff61b2c-1dbb-485a-8367-415b5df9cefd&quot;,&quot;translation_id&quot;:&quot;26753965-173d-453c-9715-f9aab1d6d4d6&quot;}', 'https://olympics.com/en/news/paris-2024-france-stars-athletes-leon-marchand-clarisse-agbegnenou-antoine-dupont-victor-wembanyama&quot;,&quot;content_id&quot;:&quot;cbf81d33-caa7-4697-9020-1ebc1e71b589&quot;,&quot;translation_id&quot;:&quot;0a56b069-e859-40b4-8901-a8a74bce025b&quot;}', 'https://olympics.com/en/news/usa-women-take-first-ever-foil-fencing-gold-in-team-competition-paris-2024&quot;,&quot;content_id&quot;:&quot;c624e3af-5317-474f-bc38-57fdc9ee8a2b&quot;,&quot;translation_id&quot;:&quot;c8ec2577-d7dd-468b-b2c3-a0aec8502a64&quot;}', 'https://olympics.com/en/news/shooting-refugee-luna-solomon-paris-2024-bows-out&quot;,&quot;content_id&quot;:&quot;891b6b62-44ab-46a3-85d1-bb72be784aa6&quot;,&quot;translation_id&quot;:&quot;0e380142-a38e-41f4-bd1d-c071c9c62a16&quot;}', 'https://olympics.com/en/news/jeux-de-paris-2024-olympics-champions-park-wins-supporters-hearts&quot;,&quot;content_id&quot;:&quot;3956abd4-b812-476d-a23e-d89157d1e0e4&quot;,&quot;translation_id&quot;:&quot;ff0120a5-6c2a-41cb-acae-829ba4a1b077&quot;}', 'https://olympics.com/en/news/paris-2024-boxing-all-results-as-arlen-cardrona-lopez-and-cristian-javier-pinales-take-bronze-in-men-s-80kg&quot;,&quot;content_id&quot;:&quot;6a692167-b521-44d6-acfb-7304c476a26a&quot;,&quot;translation_id&quot;:&quot;5d6349ab-3aa9-40d1-9754-34608110cab6&quot;}', 'https://olympics.com/en/news/refugee-runner-farida-abaroge-records-seasons-best-womens-1500m-qualifying-paris-2024-olympics&quot;,&quot;content_id&quot;:&quot;73670b30-677e-4d23-b636-397c876a90a8&quot;,&quot;translation_id&quot;:&quot;1161c7ff-d241-4aec-9bc6-d52e6113adc5&quot;}', 'https://olympics.com/en/news/usa-gold-mens-freestyle-relay-paris-2024', 'https://olympics.com/en/athletes/rebeca-andrade', 'https://olympics.com/en/news/simone-biles-on-first-all-black-olympic-gymnastics-podium-we-knew-the-impact-it-would-make-exclusive', 'https://olympics.com/en/news/great-britain-paris-2024-preview-highlights-athletes-2-august', 'https://olympics.com/en/news/paris-2024-cycling-team-australia-s-saya-sakakibara-pumps-and-jumps-to-gold-in-women-s-bmx-racing&quot;,&quot;content_id&quot;:&quot;8bcf38c0-d12d-4e0b-a0a1-0763eb42b2dd&quot;,&quot;translation_id&quot;:&quot;34f412aa-cae7-4cea-8d83-80ef9ec6f07e&quot;}', 'https://olympics.com/en/news/paris-2024-canoe-sprint-czechia-josef-dostal-wins-first-gold-beat-hungarian-duo-men-s-kayak-single-1000m-final&quot;,&quot;content_id&quot;:&quot;37c593b9-1b10-4b86-bebe-eb44b7a8447d&quot;,&quot;translation_id&quot;:&quot;21fc0782-b8ae-4aa5-98de-a591abe3ce3d&quot;}', 'https://olympics.com/en/athletes/yekta-jamali-galeh', 'https://olympics.com/en/news/paris-2024-athletics-team-usa-defend-gold-in-mens-4x400m-relay-olympic-record&quot;,&quot;content_id&quot;:&quot;c413f4dd-fc77-47ae-a3bd-790ba67c7b42&quot;,&quot;translation_id&quot;:&quot;ce8b994e-bb96-427a-b81e-49a7e6f88d58&quot;}', 'https://olympics.com/en/news/cindy-ngamba-history-first-refugee-olympic-medal-paris-2024-boxing-semi-finals', 'https://olympics.com/en/news/paris-2024-rowing-all-results-karolien-florijn-emma-twigg-womens-single-sculls-gold&quot;,&quot;content_id&quot;:&quot;ef592b59-eb14-4044-8784-d7e2562cc158&quot;,&quot;translation_id&quot;:&quot;95ff9cd4-b614-4ba0-ab33-717af74daa62&quot;}', 'https://olympics.com/en/news/paris-2024-olympics-india-schedule-august-4-sunday', 'https://olympics.com/en/news/paris-2024-olympics-simone-biles-submits-new-element-on-the-uneven-bars&quot;,&quot;content_id&quot;:&quot;c1415a37-a856-4926-9864-26af5ecc3611&quot;,&quot;translation_id&quot;:&quot;4f8235a5-4cd3-4741-8af0-7abe640fa783&quot;}', 'https://olympics.com/en/news/wayde-van-niekerk-s-individual-medal-hopes-end-as-he-crashes-out-of-200m-semis', 'https://olympics.com/en/news/what-are-the-phryges-mascots-paris-2024-olympics-paralympics', 'https://olympics.com/en/news/interview-refugee-athletes-yahya-al-ghotany-cindy-ngamba-paris-2024-opening-ceremony-flagbearers', 'https://olympics.com/en/news/the-rise-of-nicola-tuthill-paris-2024&quot;,&quot;content_id&quot;:&quot;c65d0da2-a5fb-4f01-9efc-ebcbdd6087c9&quot;,&quot;translation_id&quot;:&quot;c314d2f6-de85-4cb8-b6d0-28352c2a4607&quot;}', 'https://olympics.com/en/news/paris-2024-judo-all-results-as-croatias-barbara-matic-takes-70kg-gold&quot;,&quot;content_id&quot;:&quot;48f0ada5-dcb4-40d7-855f-f94fc7af9077&quot;,&quot;translation_id&quot;:&quot;a8f3cf41-ae82-4301-9f24-8acf020acc8c&quot;}', 'https://olympics.com/en/news/sha-carri-richardson-finally-gets-olympic-gold-4x100m-relay', 'https://olympics.com/en/news/paris-2024-olympics-water-polo-australia-vs-usa-quarter-finals-live-time', 'https://olympics.com/en/news/sakurai-tsugumi-wins-gold-paris-2024-wrestling-women-freestyle-57kg', 'https://olympics.com/en/news/paris-2024-olympics-award-athletes-podium-medals-poster-mascot', 'https://olympics.com/en/news/paris-2024-olympics-women-golf-india-round-3-results-scores&quot;,&quot;content_id&quot;:&quot;045480ca-1de8-455e-a7b0-314ce317713d&quot;,&quot;translation_id&quot;:&quot;5dcfc80d-4a7e-423c-a991-b8534ae636a2&quot;}', 'https://olympics.com/en/news/club-france-de-paris-2024-le-programme-du-jour-10-aout&quot;,&quot;content_id&quot;:&quot;f1f6126e-d14a-4422-aec7-2806d2653e55&quot;,&quot;translation_id&quot;:&quot;0b685b2a-44d6-438e-9046-39c4d4e5949d&quot;}', 'https://olympics.com/en/news/club-france-paris-2024-day-s-programme-2-august', 'https://olympics.com/en/news/letsile-tebogo-stuns-noah-lyles-to-win-mens-200m-gold', 'https://olympics.com/en/news/lebron-james-clutch-once-again-in-team-usa-men-s-basketball-paris-2024-tune-up-win-over-germany', 'https://olympics.com/en/news/paris-2024-olympics-jagger-eaton-exclusive-history', 'https://olympics.com/en/news/paris-2024-olympics-satwiksairaj-rankireddy-chirag-shetty-badminton-schedule', 'https://olympics.com/en/news/paris-2024-olympics-archery-india-men-team-quarter-finals-results', 'https://olympics.com/en/news/paris-2024-olympics-australia-vs-canada-basketball-men-group-match-2', 'https://olympics.com/en/news/paris-2024-olympics-rohan-bopanna-tennis-men-doubles-schedule', 'https://olympics.com/en/news/paris-2024-swimming-hungary-hubert-kos-200m-backstroke&quot;,&quot;content_id&quot;:&quot;384b86f0-8e14-4ebe-8f00-57626859d22b&quot;,&quot;translation_id&quot;:&quot;bac9cdb7-26e1-413d-a188-6035e9a9486d&quot;}', 'https://olympics.com/en/news/paris-2024-usa-football-women-opening-win-zambia&quot;,&quot;content_id&quot;:&quot;3faeeb3e-ccab-47b8-b0d8-41bb3deae14c&quot;,&quot;translation_id&quot;:&quot;73f9dfc1-930f-476b-97ff-ce4e6dba2850&quot;}', 'https://olympics.com/en/news/paris-2024-usa-flagbearer-coco-gauff-le-bron-james-pins', 'https://olympics.com/en/news/dreams-come-true-refugee-olympic-team-athletes-paris-2024', 'https://olympics.com/en/news/paris-2024-olympics-india-vs-germany-hockey-men-semi-final&quot;,&quot;content_id&quot;:&quot;abc89193-d244-40da-be6d-9518984f7fac&quot;,&quot;translation_id&quot;:&quot;31e79741-8ed6-4470-91e6-a8ffb835b765&quot;}', 'https://olympics.com/en/news/paris-2024-olympics-india-schedule-july-27-saturday&quot;,&quot;content_id&quot;:&quot;f062c265-ab1f-4647-bad3-72fec05dc617&quot;,&quot;translation_id&quot;:&quot;3f5f8c8c-f8da-48c0-97f2-65265325c1dc&quot;}', 'https://olympics.com/en/news/paris-2024-team-canada-highlights', 'https://olympics.com/en/news/why-names-dont-matter-as-nadal-alcaraz-aim-for-gold', 'https://olympics.com/en/news/kyle-chalmers-tattoo-meaning-australia-swimmer&quot;,&quot;content_id&quot;:&quot;c2880abc-1ead-4726-89cf-2c2a74378aeb&quot;,&quot;translation_id&quot;:&quot;87460be1-7836-42b3-9349-4390dd799010&quot;}', 'https://olympics.com/en/news/paris-2024-andy-murray-retirement-olympic-games&quot;,&quot;content_id&quot;:&quot;24679c67-4020-422d-8d86-890a03699dfb&quot;,&quot;translation_id&quot;:&quot;c478ec77-1806-4a46-aeee-3cb65d658a31&quot;}', 'https://olympics.com/en/news/modern-pentathlon-paris-2024-olympics-preview-schedule-watch', 'https://olympics.com/en/news/thierry-henry-reinvented-coach-france-paris-2024&quot;,&quot;content_id&quot;:&quot;eb860e5a-1a3c-4e64-b0ef-c16e1bfad6e3&quot;,&quot;translation_id&quot;:&quot;1784a1f1-eeac-4add-a0ec-47d58203697b&quot;}', 'https://olympics.com/en/news/surfing-paris-2024-alonso-correa-the-boy-who-loved-the-sea&quot;,&quot;content_id&quot;:&quot;6b842e4b-c59f-422f-a0de-e83cd7064e0a&quot;,&quot;translation_id&quot;:&quot;bbbcdefe-5240-4385-890c-230f6433c7bb&quot;}', 'https://olympics.com/en/news/thierry-henry-reinvented-coach-france-paris-2024', 'https://olympics.com/en/news/paris-2024-sailing-all-results-tom-reuveny-clinches-windsurfing-men-s-gold&quot;,&quot;content_id&quot;:&quot;95483c1c-2d06-43b4-bbdc-71a849d686fb&quot;,&quot;translation_id&quot;:&quot;5f056cc2-a6fc-49e3-90d1-b565013be9b4&quot;}', 'https://olympics.com/en/news/paris-2024-olympics-men-golf-india-round-3-results-scores&quot;,&quot;content_id&quot;:&quot;1eca35fa-c291-4711-941a-a4a352199cd5&quot;,&quot;translation_id&quot;:&quot;e7dc8790-9e5e-4933-83de-b22e63856882&quot;}', 'https://olympics.com/en/news/paris-2024-olympics-tennis-novak-djokovic-vs-carlos-alcaraz-how-watch-australia&quot;,&quot;content_id&quot;:&quot;927b6a84-5cb7-41b1-bbbf-8cfee4e9c574&quot;,&quot;translation_id&quot;:&quot;1a6b5384-2475-4c67-9f89-60bafc55d01c&quot;}', 'https://olympics.com/en/news/iconic-venues-gender-parity-what-makes-olympic-games-paris-2024-special', 'https://olympics.com/en/news/team-behind-eliud-kipchoge-marathon&quot;,&quot;content_id&quot;:&quot;03255e0a-cded-409b-b25e-66610ed293fe&quot;,&quot;translation_id&quot;:&quot;ad781df4-52b4-4def-96c3-b86eb586fbc3&quot;}', 'https://olympics.com/en/news/paris-2024-athletics-results-usa-win-womens-4x400m-relay&quot;,&quot;content_id&quot;:&quot;99e982ad-3841-49c1-8a8b-7f9248d0ff46&quot;,&quot;translation_id&quot;:&quot;d807949a-7670-4d5e-9833-3279485f7cfa&quot;}', 'https://olympics.com/en/athletes/eyeru-gebru', 'https://olympics.com/en/news/paris-2024-basketball-men-wembanyama-france-japan', 'https://olympics.com/en/news/paris-2024-hockey-day-five-roundup', 'https://olympics.com/en/news/records-stats-facts-of-historic-paris-2024', 'https://olympics.com/en/news/paris-2024-olympics-lebron-james-closer-for-usa-men-basketball&quot;,&quot;content_id&quot;:&quot;acf41f4c-cc46-47e1-85a2-53e17142c826&quot;,&quot;translation_id&quot;:&quot;93b60b7c-6e37-44af-b9ff-1a1b0cfb6cf1&quot;}', 'https://olympics.com/en/news/paris-2024-olympics-vinesh-phogat-wrestling-schedule-women-50kg&quot;,&quot;content_id&quot;:&quot;4995c806-374f-43d5-8cd2-f48d7d150f03&quot;,&quot;translation_id&quot;:&quot;f2c2753a-defa-41ad-b6dd-b0794b677302&quot;}', 'https://olympics.com/en/news/paris-2024-olympics-ariana-grande-lady-gaga-tom-cruise-celebrities-womens-gymnastics-simone-biles-paris&quot;,&quot;content_id&quot;:&quot;cc32b092-e308-453d-883a-ad3456be549e&quot;,&quot;translation_id&quot;:&quot;3ce21fed-3e8b-42be-9e37-be842b35e206&quot;}', 'https://olympics.com/en/news/supermums-conquer-paris-agbegnenou-osaka-fraser-pryce&quot;,&quot;content_id&quot;:&quot;dd929954-2798-43ac-b955-b3cb7a08a752&quot;,&quot;translation_id&quot;:&quot;d9a2befe-ebad-45d3-b085-d9fdaa990a91&quot;}', 'https://olympics.com/en/news/paris-2024-olympics-refugee-canoet-amir-rezanejad-hassanjani-eliminated&quot;,&quot;content_id&quot;:&quot;92252197-ad12-4077-8c28-a32107b81702&quot;,&quot;translation_id&quot;:&quot;74448b05-c2f6-4176-b00d-223c218e52ee&quot;}', 'https://olympics.com/en/news/badminton-paris-2024-olympics-jonatan-christie', 'https://olympics.com/en/news/paris-2024-olympics-australia-schedule-august-3-friday-medal-events&quot;,&quot;content_id&quot;:&quot;5b0d7b7f-aac8-48a9-8b08-f96d3f2f9bc4&quot;,&quot;translation_id&quot;:&quot;aa3ec38b-68cd-443e-a7da-698b05b5e587&quot;}', 'https://olympics.com/en/news/usa-surfing-caroline-marks-going-for-paris-gold&quot;,&quot;content_id&quot;:&quot;2045fc20-4153-4774-ade2-b2ea98d8aed3&quot;,&quot;translation_id&quot;:&quot;00f2e395-0d1e-4517-8ba3-a584df3a4d90&quot;}', 'https://olympics.com/en/news/paris-2024-olympics-nicola-olyslagers-athletics-high-jump-schedule-australia&quot;,&quot;content_id&quot;:&quot;d32ed5d1-54de-4efa-a2b9-bf182e454a3a&quot;,&quot;translation_id&quot;:&quot;877fbf81-1dff-4ad3-a3e0-1da068dbbee9&quot;}', 'https://olympics.com/en/news/paris-2024-badminton-women-doubles-results', 'https://olympics.com/en/news/paris-2024-athletes-kitaguchi-haruka-wins-olympic-javelin-results&quot;,&quot;content_id&quot;:&quot;920c7cdd-e7fc-443c-906a-b12069f36e3d&quot;,&quot;translation_id&quot;:&quot;0dded5a4-9e78-49f3-a619-7ad59817fd84&quot;}', 'https://olympics.com/en/news/chinas-xie-siyi-and-wang-zongyuan-sweep-3m-podium-paris-2024', 'https://olympics.com/en/news/paris-2024-olympics-india-gagan-narang-chef-de-mission-interview&quot;,&quot;content_id&quot;:&quot;162c429f-a081-401a-9916-a23dc4e964a3&quot;,&quot;translation_id&quot;:&quot;4806a2e3-c94b-470e-bea3-df6060af3192&quot;}', 'https://olympics.com/en/news/paris-2024-turkiye-shooting-yusuf-dikec-medal-pose', 'https://olympics.com/en/news/paris-2024-why-does-team-usas-raven-saunders-wear-a-mask-when-competing&quot;,&quot;content_id&quot;:&quot;9c402426-3f7e-4f0b-9edc-24dd5b8175ad&quot;,&quot;translation_id&quot;:&quot;417424f6-7f24-4930-9ffc-9bfede842fe7&quot;}', 'https://olympics.com/en/news/paris-2024-janja-garnbret-sport-climbing-fitness-influencer-natacha-oceane&quot;,&quot;content_id&quot;:&quot;7601f446-a5d0-4667-9864-9ece916c479a&quot;,&quot;transla

In [271]:
unique_links[:100]

['https://olympics.com/en/news/paris-2024-olympics-fencers-manon-apithy-brunet-sara-balzer-celebrates-club-france&quot;,&quot;content_id&quot;:&quot;5375d472-7428-4b30-9403-68f099c9eda5&quot;,&quot;translation_id&quot;:&quot;f4d6b92b-250c-42ea-9a96-727ded5f7986&quot;}',
 'https://olympics.com/en/news/katie-ledecky-reveals-secret-longevity-swimming&quot;,&quot;content_id&quot;:&quot;2362d088-ce20-4242-961d-2e2d87e2ffe3&quot;,&quot;translation_id&quot;:&quot;fdc6b4f4-985a-4fdb-9e28-e2cb556765c7&quot;}',
 'https://olympics.com/en/news/paris-2024-olympics-swimming-australia-results-times-medal-winners',
 'https://olympics.com/en/news/paris-2024-olympics-judo-all-results-as-japan-s-nagase-takanori-captures-his-second-consecutive-gold-medal-in-men-s-81kg',
 'https://olympics.com/en/news/usa-basketball-star-diana-taurasi-says-paris-2024-are-her-final-olympic-games&quot;,&quot;content_id&quot;:&quot;84da49b3-8f72-43d2-a897-21ac3bb983c5&quot;,&quot;translation_id&quot;:&quot;1a45c61f-48c5-4ec3-a485-7e1e317c7afb&quot;}',
 'https://olympics.com/en/news/jeux-olympiques-paris-2024-conclure-en-beaute',
 'https://olympics.com/en/news/paris-2024-olympics-rugby-sevens-schedule-australia&quot;,&quot;content_id&quot;:&quot;85fada01-d651-4f11-8bd9-b2d3ffda6044&quot;,&quot;translation_id&quot;:&quot;5f1ebf86-a468-4ca2-bcc7-7f81efe66e9b&quot;}',
 'https://olympics.com/en/athletes/darja-varfolomeev',
 'https://olympics.com/en/news/paris-2024-basketball-derrick-white-surprise-call-usa',
 'https://olympics.com/en/news/paris-2024-olympics-vinesh-phogat-wrestling-schedule-women-50kg',
 'https://olympics.com/en/news/ashwini-ponnappa-indian-badminton-last-olympics-paris-2024&quot;,&quot;content_id&quot;:&quot;6b0302fb-efa2-4d7a-9628-dbbb0720e64f&quot;,&quot;translation_id&quot;:&quot;378ba37b-1694-4bc0-83ce-df9528699c1a&quot;}',
 'https://olympics.com/en/news/paris-2024-olympics-australia-road-cycling-lucas-plapp-injury-replacement',
 'https://olympics.com/en/news/paris-2024-fencing-hong-kong-china-cheung-ka-long-olympic-champion-mens-foil-individual&quot;,&quot;content_id&quot;:&quot;3f83ee99-6aff-4da6-a18e-e6c5cfe12530&quot;,&quot;translation_id&quot;:&quot;c09b61de-30ba-44b1-931d-83244d0f3363&quot;}',
 'https://olympics.com/en/news/im-aeji-takes-womens-54kg-bronze-boxing-paris-2024',
 'https://olympics.com/en/news/skateboarding-women-park-preview-full-schedule-and-how-to-watch-live',
 'https://olympics.com/en/news/keely-hodgkinson-olympic-gold-future-keys-to-success',
 'https://olympics.com/en/news/paris-2024-olympics-why-you-dont-want-to-miss-triathlon&quot;,&quot;content_id&quot;:&quot;5cb09ac9-0a2f-40cc-8fac-ab1da6a5d492&quot;,&quot;translation_id&quot;:&quot;d1992ddd-9910-4f21-b086-29e60ca5cc27&quot;}',
 'https://olympics.com/en/news/paris-2024-men-volleyball-semi-finals&quot;,&quot;content_id&quot;:&quot;9d00046a-1bd4-4a12-bcd8-bf95313ace87&quot;,&quot;translation_id&quot;:&quot;dd8344ab-8cc5-48d0-b0ba-a94d58e1f95c&quot;}',
 'https://olympics.com/en/news/paris-2024-olympics-table-tennis-india-vs-china-round-of-16-results&quot;,&quot;content_id&quot;:&quot;670b9673-e220-438b-8250-1259d59cab42&quot;,&quot;translation_id&quot;:&quot;00dadb4d-969c-436d-9f25-32282d026a4d&quot;}',
 'https://olympics.com/en/news/paris-2024-olympics-australia-vs-usa-hockey-women-group-match-3',
 'https://olympics.com/en/news/paris-2024-skateboard-street-men-horigome-eaton-huston',
 'https://olympics.com/en/news/paris-2024-olympics-pv-sindhu-badminton-schedule-women-singles',
 'https://olympics.com/en/news/paris-2024-badminton-women-doubles-results&quot;,&quot;content_id&quot;:&quot;a5dd1e0d-dac1-448a-a885-9d6be22d202e&quot;,&quot;translation_id&quot;:&quot;9a2ef505-a461-4011-9114-a6b2907935e8&quot;}',
 'https://olympics.com/en/news/paris-2024-olympics-badminton-india-pv-sindhu-lakshya-sen-hs-prannoy-group&quot;,&quot;content_id&quot;:&quot;0b57a165-7294-4153-8e41-d537c350dc22&quot;,&quot;translation_id&quot;:&quot;39369629-addb-4a32-ae7c-bf45bcd39afb&quot;}',
 'https://olympics.com/en/news/teen-history-maker-arisa-trew-australia-exclusive-whirldwind-paris-ulympics-medal',
 'https://olympics.com/en/news/paris-2024-basketball-men-wembanyama-france-japan&quot;,&quot;content_id&quot;:&quot;25e6a134-eac8-4b1d-b6f8-aaeb6dd494e7&quot;,&quot;translation_id&quot;:&quot;d0c25717-3320-4158-9ee4-3507a2a853d1&quot;}',
 'https://olympics.com/en/paris-2024/sports/cycling-mountain-bike',
 'https://olympics.com/en/news/paris-2024-olympics-archery-india-women-team-quarter-finals-results',
 'https://olympics.com/en/news/paris-2024-olympics-women-basketball-australia-vs-serbia-quarter-finals-live-time',
 'https://olympics.com/en/news/paris-2024-olympics-full-list-ioc-national-olympic-committee-codes&quot;,&quot;content_id&quot;:&quot;fe35176b-c5b8-438c-82de-a98770119fd0&quot;,&quot;translation_id&quot;:&quot;c0c256ba-5e25-4c98-a454-b1072e0c00d1&quot;}',
 'https://olympics.com/en/paris-2024/sports/judo',
 'https://olympics.com/en/news/paris-2024-great-britain-preview-athletes-7-august',
 'https://olympics.com/en/news/akani-simbine-narrowly-misses-podium-in-third-consecutive-olympic-100m-final',
 'https://olympics.com/en/news/paris-2024-olympics-michelle-jenneke-athletics-100m-hurdles-schedule',
 'https://olympics.com/en/news/paris-2024-olympic-paralympic-games-why-track-purple-stade-de-france&quot;,&quot;content_id&quot;:&quot;96ab8b55-38e8-4255-a643-92643b178990&quot;,&quot;translation_id&quot;:&quot;b62e8d03-7c54-4216-8bb5-d89386b8b69c&quot;}',
 'https://olympics.com/en/news/paris-2024-olympics-hockey-netherlands-vs-australia-quarter-finals-live-time&quot;,&quot;content_id&quot;:&quot;5d6faa55-b147-4f3f-b49d-a9252afbfe19&quot;,&quot;translation_id&quot;:&quot;863b26e6-319e-4c80-a2e0-3b1a493d59b2&quot;}',
 'https://olympics.com/en/news/paris-2024-sailing-all-results-italy-sail-to-mixed-multihull-olympic-gold&quot;,&quot;content_id&quot;:&quot;d8eb122b-7078-4aa7-82d4-b29ae41ebf42&quot;,&quot;translation_id&quot;:&quot;1cf5c202-efad-40d9-8cb3-6486242afe0c&quot;}',
 'https://olympics.com/en/news/jade-carey-s-happy-end-in-paris-bronze-olympics-vault&quot;,&quot;content_id&quot;:&quot;9afb38b6-f787-48d8-9020-e840685ae6bb&quot;,&quot;translation_id&quot;:&quot;e68e75d0-8259-4053-959b-8aa79f408911&quot;}',
 'https://olympics.com/en/news/paris-2024-athletics-team-gb-keely-hodgkinson-charges-to-victory-womens-800m-final',
 'https://olympics.com/en/news/paris-2024-basketball-women-usa-win-belgium&quot;,&quot;content_id&quot;:&quot;dff61b2c-1dbb-485a-8367-415b5df9cefd&quot;,&quot;translation_id&quot;:&quot;26753965-173d-453c-9715-f9aab1d6d4d6&quot;}',
 'https://olympics.com/en/news/paris-2024-france-stars-athletes-leon-marchand-clarisse-agbegnenou-antoine-dupont-victor-wembanyama&quot;,&quot;content_id&quot;:&quot;cbf81d33-caa7-4697-9020-1ebc1e71b589&quot;,&quot;translation_id&quot;:&quot;0a56b069-e859-40b4-8901-a8a74bce025b&quot;}',
 'https://olympics.com/en/news/usa-women-take-first-ever-foil-fencing-gold-in-team-competition-paris-2024&quot;,&quot;content_id&quot;:&quot;c624e3af-5317-474f-bc38-57fdc9ee8a2b&quot;,&quot;translation_id&quot;:&quot;c8ec2577-d7dd-468b-b2c3-a0aec8502a64&quot;}',
 'https://olympics.com/en/news/shooting-refugee-luna-solomon-paris-2024-bows-out&quot;,&quot;content_id&quot;:&quot;891b6b62-44ab-46a3-85d1-bb72be784aa6&quot;,&quot;translation_id&quot;:&quot;0e380142-a38e-41f4-bd1d-c071c9c62a16&quot;}',
 'https://olympics.com/en/news/jeux-de-paris-2024-olympics-champions-park-wins-supporters-hearts&quot;,&quot;content_id&quot;:&quot;3956abd4-b812-476d-a23e-d89157d1e0e4&quot;,&quot;translation_id&quot;:&quot;ff0120a5-6c2a-41cb-acae-829ba4a1b077&quot;}',
 'https://olympics.com/en/news/paris-2024-boxing-all-results-as-arlen-cardrona-lopez-and-cristian-javier-pinales-take-bronze-in-men-s-80kg&quot;,&quot;content_id&quot;:&quot;6a692167-b521-44d6-acfb-7304c476a26a&quot;,&quot;translation_id&quot;:&quot;5d6349ab-3aa9-40d1-9754-34608110cab6&quot;}',
 'https://olympics.com/en/news/refugee-runner-farida-abaroge-records-seasons-best-womens-1500m-qualifying-paris-2024-olympics&quot;,&quot;content_id&quot;:&quot;73670b30-677e-4d23-b636-397c876a90a8&quot;,&quot;translation_id&quot;:&quot;1161c7ff-d241-4aec-9bc6-d52e6113adc5&quot;}',
 'https://olympics.com/en/news/usa-gold-mens-freestyle-relay-paris-2024',
 'https://olympics.com/en/athletes/rebeca-andrade',
 'https://olympics.com/en/news/simone-biles-on-first-all-black-olympic-gymnastics-podium-we-knew-the-impact-it-would-make-exclusive',
 'https://olympics.com/en/news/great-britain-paris-2024-preview-highlights-athletes-2-august',
 'https://olympics.com/en/news/paris-2024-cycling-team-australia-s-saya-sakakibara-pumps-and-jumps-to-gold-in-women-s-bmx-racing&quot;,&quot;content_id&quot;:&quot;8bcf38c0-d12d-4e0b-a0a1-0763eb42b2dd&quot;,&quot;translation_id&quot;:&quot;34f412aa-cae7-4cea-8d83-80ef9ec6f07e&quot;}',
 'https://olympics.com/en/news/paris-2024-canoe-sprint-czechia-josef-dostal-wins-first-gold-beat-hungarian-duo-men-s-kayak-single-1000m-final&quot;,&quot;content_id&quot;:&quot;37c593b9-1b10-4b86-bebe-eb44b7a8447d&quot;,&quot;translation_id&quot;:&quot;21fc0782-b8ae-4aa5-98de-a591abe3ce3d&quot;}',
 'https://olympics.com/en/athletes/yekta-jamali-galeh',
 'https://olympics.com/en/news/paris-2024-athletics-team-usa-defend-gold-in-mens-4x400m-relay-olympic-record&quot;,&quot;content_id&quot;:&quot;c413f4dd-fc77-47ae-a3bd-790ba67c7b42&quot;,&quot;translation_id&quot;:&quot;ce8b994e-bb96-427a-b81e-49a7e6f88d58&quot;}',
 'https://olympics.com/en/news/cindy-ngamba-history-first-refugee-olympic-medal-paris-2024-boxing-semi-finals',
 'https://olympics.com/en/news/paris-2024-rowing-all-results-karolien-florijn-emma-twigg-womens-single-sculls-gold&quot;,&quot;content_id&quot;:&quot;ef592b59-eb14-4044-8784-d7e2562cc158&quot;,&quot;translation_id&quot;:&quot;95ff9cd4-b614-4ba0-ab33-717af74daa62&quot;}',
 'https://olympics.com/en/news/paris-2024-olympics-india-schedule-august-4-sunday',
 'https://olympics.com/en/news/paris-2024-olympics-simone-biles-submits-new-element-on-the-uneven-bars&quot;,&quot;content_id&quot;:&quot;c1415a37-a856-4926-9864-26af5ecc3611&quot;,&quot;translation_id&quot;:&quot;4f8235a5-4cd3-4741-8af0-7abe640fa783&quot;}',
 'https://olympics.com/en/news/wayde-van-niekerk-s-individual-medal-hopes-end-as-he-crashes-out-of-200m-semis',
 'https://olympics.com/en/news/what-are-the-phryges-mascots-paris-2024-olympics-paralympics',
 'https://olympics.com/en/news/interview-refugee-athletes-yahya-al-ghotany-cindy-ngamba-paris-2024-opening-ceremony-flagbearers',
 'https://olympics.com/en/news/the-rise-of-nicola-tuthill-paris-2024&quot;,&quot;content_id&quot;:&quot;c65d0da2-a5fb-4f01-9efc-ebcbdd6087c9&quot;,&quot;translation_id&quot;:&quot;c314d2f6-de85-4cb8-b6d0-28352c2a4607&quot;}',
 'https://olympics.com/en/news/paris-2024-judo-all-results-as-croatias-barbara-matic-takes-70kg-gold&quot;,&quot;content_id&quot;:&quot;48f0ada5-dcb4-40d7-855f-f94fc7af9077&quot;,&quot;translation_id&quot;:&quot;a8f3cf41-ae82-4301-9f24-8acf020acc8c&quot;}',
 'https://olympics.com/en/news/sha-carri-richardson-finally-gets-olympic-gold-4x100m-relay',
 'https://olympics.com/en/news/paris-2024-olympics-water-polo-australia-vs-usa-quarter-finals-live-time',
 'https://olympics.com/en/news/sakurai-tsugumi-wins-gold-paris-2024-wrestling-women-freestyle-57kg',
 'https://olympics.com/en/news/paris-2024-olympics-award-athletes-podium-medals-poster-mascot',
 'https://olympics.com/en/news/paris-2024-olympics-women-golf-india-round-3-results-scores&quot;,&quot;content_id&quot;:&quot;045480ca-1de8-455e-a7b0-314ce317713d&quot;,&quot;translation_id&quot;:&quot;5dcfc80d-4a7e-423c-a991-b8534ae636a2&quot;}',
 'https://olympics.com/en/news/club-france-de-paris-2024-le-programme-du-jour-10-aout&quot;,&quot;content_id&quot;:&quot;f1f6126e-d14a-4422-aec7-2806d2653e55&quot;,&quot;translation_id&quot;:&quot;0b685b2a-44d6-438e-9046-39c4d4e5949d&quot;}',
 'https://olympics.com/en/news/club-france-paris-2024-day-s-programme-2-august',
 'https://olympics.com/en/news/letsile-tebogo-stuns-noah-lyles-to-win-mens-200m-gold',
 'https://olympics.com/en/news/lebron-james-clutch-once-again-in-team-usa-men-s-basketball-paris-2024-tune-up-win-over-germany',
 'https://olympics.com/en/news/paris-2024-olympics-jagger-eaton-exclusive-history',
 'https://olympics.com/en/news/paris-2024-olympics-satwiksairaj-rankireddy-chirag-shetty-badminton-schedule',
 'https://olympics.com/en/news/paris-2024-olympics-archery-india-men-team-quarter-finals-results',
 'https://olympics.com/en/news/paris-2024-olympics-australia-vs-canada-basketball-men-group-match-2',
 'https://olympics.com/en/news/paris-2024-olympics-rohan-bopanna-tennis-men-doubles-schedule',
 'https://olympics.com/en/news/paris-2024-swimming-hungary-hubert-kos-200m-backstroke&quot;,&quot;content_id&quot;:&quot;384b86f0-8e14-4ebe-8f00-57626859d22b&quot;,&quot;translation_id&quot;:&quot;bac9cdb7-26e1-413d-a188-6035e9a9486d&quot;}',
 'https://olympics.com/en/news/paris-2024-usa-football-women-opening-win-zambia&quot;,&quot;content_id&quot;:&quot;3faeeb3e-ccab-47b8-b0d8-41bb3deae14c&quot;,&quot;translation_id&quot;:&quot;73f9dfc1-930f-476b-97ff-ce4e6dba2850&quot;}',
 'https://olympics.com/en/news/paris-2024-usa-flagbearer-coco-gauff-le-bron-james-pins',
 'https://olympics.com/en/news/dreams-come-true-refugee-olympic-team-athletes-paris-2024',
 'https://olympics.com/en/news/paris-2024-olympics-india-vs-germany-hockey-men-semi-final&quot;,&quot;content_id&quot;:&quot;abc89193-d244-40da-be6d-9518984f7fac&quot;,&quot;translation_id&quot;:&quot;31e79741-8ed6-4470-91e6-a8ffb835b765&quot;}',
 'https://olympics.com/en/news/paris-2024-olympics-india-schedule-july-27-saturday&quot;,&quot;content_id&quot;:&quot;f062c265-ab1f-4647-bad3-72fec05dc617&quot;,&quot;translation_id&quot;:&quot;3f5f8c8c-f8da-48c0-97f2-65265325c1dc&quot;}',
 'https://olympics.com/en/news/paris-2024-team-canada-highlights',
 'https://olympics.com/en/news/why-names-dont-matter-as-nadal-alcaraz-aim-for-gold',
 'https://olympics.com/en/news/kyle-chalmers-tattoo-meaning-australia-swimmer&quot;,&quot;content_id&quot;:&quot;c2880abc-1ead-4726-89cf-2c2a74378aeb&quot;,&quot;translation_id&quot;:&quot;87460be1-7836-42b3-9349-4390dd799010&quot;}',
 'https://olympics.com/en/news/paris-2024-andy-murray-retirement-olympic-games&quot;,&quot;content_id&quot;:&quot;24679c67-4020-422d-8d86-890a03699dfb&quot;,&quot;translation_id&quot;:&quot;c478ec77-1806-4a46-aeee-3cb65d658a31&quot;}',
 'https://olympics.com/en/news/modern-pentathlon-paris-2024-olympics-preview-schedule-watch',
 'https://olympics.com/en/news/thierry-henry-reinvented-coach-france-paris-2024&quot;,&quot;content_id&quot;:&quot;eb860e5a-1a3c-4e64-b0ef-c16e1bfad6e3&quot;,&quot;translation_id&quot;:&quot;1784a1f1-eeac-4add-a0ec-47d58203697b&quot;}',
 'https://olympics.com/en/news/surfing-paris-2024-alonso-correa-the-boy-who-loved-the-sea&quot;,&quot;content_id&quot;:&quot;6b842e4b-c59f-422f-a0de-e83cd7064e0a&quot;,&quot;translation_id&quot;:&quot;bbbcdefe-5240-4385-890c-230f6433c7bb&quot;}',
 'https://olympics.com/en/news/thierry-henry-reinvented-coach-france-paris-2024',
 'https://olympics.com/en/news/paris-2024-sailing-all-results-tom-reuveny-clinches-windsurfing-men-s-gold&quot;,&quot;content_id&quot;:&quot;95483c1c-2d06-43b4-bbdc-71a849d686fb&quot;,&quot;translation_id&quot;:&quot;5f056cc2-a6fc-49e3-90d1-b565013be9b4&quot;}',
 'https://olympics.com/en/news/paris-2024-olympics-men-golf-india-round-3-results-scores&quot;,&quot;content_id&quot;:&quot;1eca35fa-c291-4711-941a-a4a352199cd5&quot;,&quot;translation_id&quot;:&quot;e7dc8790-9e5e-4933-83de-b22e63856882&quot;}',
 'https://olympics.com/en/news/paris-2024-olympics-tennis-novak-djokovic-vs-carlos-alcaraz-how-watch-australia&quot;,&quot;content_id&quot;:&quot;927b6a84-5cb7-41b1-bbbf-8cfee4e9c574&quot;,&quot;translation_id&quot;:&quot;1a6b5384-2475-4c67-9f89-60bafc55d01c&quot;}',
 'https://olympics.com/en/news/iconic-venues-gender-parity-what-makes-olympic-games-paris-2024-special',
 'https://olympics.com/en/news/team-behind-eliud-kipchoge-marathon&quot;,&quot;content_id&quot;:&quot;03255e0a-cded-409b-b25e-66610ed293fe&quot;,&quot;translation_id&quot;:&quot;ad781df4-52b4-4def-96c3-b86eb586fbc3&quot;}',
 'https://olympics.com/en/news/paris-2024-athletics-results-usa-win-womens-4x400m-relay&quot;,&quot;content_id&quot;:&quot;99e982ad-3841-49c1-8a8b-7f9248d0ff46&quot;,&quot;translation_id&quot;:&quot;d807949a-7670-4d5e-9833-3279485f7cfa&quot;}',
 'https://olympics.com/en/athletes/eyeru-gebru',
 'https://olympics.com/en/news/paris-2024-basketball-men-wembanyama-france-japan',
 'https://olympics.com/en/news/paris-2024-hockey-day-five-roundup']

The code below will get the text in the articles and save it in a text file. Each of these articles will serve as our list of "documents" that we want to retrieve from

**Note:** This code segment to download the articles takes quite a long time to run. For convenience, you can use the pre-downloaded one found in ``paris_olympics_articles.zip`` for the rest of the assignment.

In [128]:
# # optional if you want to download it yourself.

# from bs4 import BeautifulSoup
# HEADERS = {
#     "Accept": "application/json, text/plain, */*", 
#     "Accept-Encoding": "gzip, deflate, br, zstd", 
#     "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
#     "Connection": "keep-alive", 
#     "Referer": "",
#     "Sec-Fetch-Dest": "empty", 
#     "Sec-Fetch-Mode": "cors", 
#     "Sec-Fetch-Site":"same-site",  
#     "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
# }
# output_folder = "paris_olympics_articles"
# os.makedirs(output_folder,exist_ok=True)

# for i, link in enumerate(tqdm(unique_links)):
#     page = requests.get(link,headers=HEADERS)
#     soup = BeautifulSoup(page.content, "html.parser")
#     div_content = soup.find(id="globalTracking")
#     if div_content is not None:
#         page_text = soup.find(id="globalTracking").text
    
#         with open("{}/{:05d}.txt".format(output_folder,i),"w", encoding="utf-8") as f:
#             f.write(page_text)

Note: If this code segment fails to run for some reason, you can use the pre-downloaded one found in ``paris_olympics_articles.zip``.

In [129]:
import zipfile

# Define the ZIP file path
zip_file = "paris_olympics_articles.zip"

# Extract the contents of the ZIP file into the current directory
with zipfile.ZipFile(zip_file, 'r') as z:
    z.extractall(".")  # Extract directly to the current folder

print("Extracted contents into the current folder!")

Extracted contents into the current folder!

In [130]:
raw_doc_texts = []
output_folder = "paris_olympics_articles"
for doc in glob.glob("{}/*.txt".format(output_folder)):
    with open(doc, 'r', encoding="utf-8") as f:
        raw_doc_texts.append(f.read().strip())

In [131]:
print("There are {} documents".format(len(raw_doc_texts)))

There are 1874 documents

We need to pre-process the raw text to get it in a useful format. 

``nltk`` is a useful library for this. It provides several tools such as a list of stopwords, tokenizer, and stemmer.

In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize # https://www.nltk.org/api/nltk.tokenize.word_tokenize.html
from nltk.stem import PorterStemmer # https://www.nltk.org/howto/stem.html
import nltk
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ningw\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ningw\Documents\Punkt...
[nltk_data]   Package punkt_tab is already up-to-date!

In [255]:
stop_words = stopwords.words('english')
symbols = "\n!\"#$%&()*+-./:;<=>?@[\]^_`{|}~"

In [256]:
############################################################
# TODO-15: Implement a function that converts the text to  #
# lowercase letters.                                       #
############################################################

def to_lowercase(text):
    """
    Converts the given text to lowercase letters.

    Args:
        text (str): The input text to be converted.

    Returns:
        str: The text converted to lowercase.
    """
    return text.lower()

############################################################
#                    End of your code.                     #
############################################################

In [257]:
#############################################################
# TODO-16: Implement a function that removes the stopwords. #
#############################################################

def remove_stopwords(text):
    """
    Removes stopwords from the given text.

    This function splits the input text into words using spaces as delimiters,
    removes any words that are present in the provided stop_words list (case-insensitive),
    and reconstructs the text without the stopwords.

    Args:
        text (str): The input text to process.
        stop_words (list of str): A list of stopwords to be removed from the text.

    Returns:
        str: The processed text with stopwords removed.
    """
    words = text.split()  # Split the text into words by spaces
    filtered_words = [word for word in words if word.lower() not in stop_words]  # Remove stopwords
    return ' '.join(filtered_words)  # Reconstruct the text from filtered words

#############################################################
#                    End of your code.                      #
#############################################################

In [258]:
###############################################################
# TODO-17: Implement a function that removes the symbols and  #
# punctuation marks.                                          #
###############################################################

def remove_symbols(text):
    """
    Removes symbols and punctuation marks from the given text.

    Args:
        text (str): The input text.

    Returns:
        str: The cleaned text with symbols and punctuation removed.
    """
    symbols = "\n!\"#$%&()*+-./:;<=>?@[\]^_`{|}~"
    cleaned_text = ''.join(char for char in text if char not in symbols)  # Remove specified symbols
    return cleaned_text

##############################################################
#                    End of your code.                       #
##############################################################

In [259]:
############################################################
# TODO-18: Implement a function that uses the stemmer to   #
# convert all the words into its stem.                     #
############################################################
def stemming(text):
    """
    Converts all the words in the given text into their stemmed form.

    Args:
        text (str): The input text to process.

    Returns:
        str: The text with all words converted into their stemmed form.
    """
    stemmer = PorterStemmer()  # Initialize the stemmer
    words = text.split()  # Split the text into words
    stemmed_words = [stemmer.stem(word) for word in words]  # Stem each word
    return ' '.join(stemmed_words)  # Reconstruct the text from stemmed words


############################################################
#                    End of your code.                     #
############################################################

In [260]:
############################################################
# TODO-19: Implement a function that combines all the      #
# preprocessing steps and outputs a word tokenized version #
# of the text.                                             #
############################################################

def preprocess(text):
    """
    Combines all preprocessing steps and outputs a word-tokenized version of the text.

    Args:
        text (str): The input text to preprocess.
        stop_words (list of str): A list of stopwords to be removed.

    Returns:
        list of str: A word-tokenized and preprocessed version of the text.
    """
    # Step 1: Convert text to lowercase
    text = text.lower()
    
    # Step 2: Remove symbols and punctuation
    symbols = "\n!\"#$%&()*+-./:;<=>?@[\]^_`{|}~“”"
    text = ''.join(char for char in text if char not in symbols)
    
    # Step 3: Remove stopwords
    words = text.split()  # Split the text into words
    filtered_words = [word for word in words if word not in stop_words]
    
    # Step 4: Stem the words
    stemmer = PorterStemmer()  # Initialize the stemmer
    stemmed_words = [stemmer.stem(word) for word in filtered_words]
    
    # Return the tokenized and preprocessed text
    return stemmed_words

############################################################
#                    End of your code.                     #
############################################################

In [261]:
import nltk
nltk.download('punkt')

def tokenize(token):
    return nltk.word_tokenize(token);
tokenize("why is this not working?");

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ningw\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

The code below will preprocess all the documents and store it in a list named ``processed_text``.

In [262]:
processed_text = []
for doc in raw_doc_texts:
    processed_text.append(preprocess(doc))

TF-IDF, as the name implies, is a combination of two terms. Term frequency, and inverse document frequency.
Let's first start with computing for the document frequency.

Document frequency basically counts how many documents does the token appear in. We can conveniently store this in a dictionary for efficient look-up later on.

**Note:** Some functions (particularly those iterating through all the documents) can take a few minutes to run. It's a good idea to test on a few subset first when debugging your code before running it completely on all the documents.

In [263]:
############################################################
# TODO-20: Compute for the document frequency of all the   #
# unique tokens in the entire dataset. Store it in a       #
# dictionary called doc_frequency, where                   #
# doc_frequency[token] contains the document counts.       #
############################################################
def compute_document_frequency(processed_text):
    """
    Computes the document frequency for all unique tokens in the dataset.

    Parameters:
    - processed_text: Nested list where each sublist contains tokens for a document.

    Returns:
    - doc_frequency: Dictionary where doc_frequency[token] contains the document count.
    """
    doc_frequency = {}

    # Iterate through each document (sublist)
    for document in processed_text:
        unique_tokens = set(document)  # Get unique tokens in the document
        for token in unique_tokens:
            if token in doc_frequency:
                doc_frequency[token] += 1
            else:
                doc_frequency[token] = 1

    return doc_frequency

# Example usage:
# Assume processed_text is a nested list of tokenized documents
processed_text_test = [
    ['pari', '2024', 'gold', 'wrestl', 'pari'],
    ['gold', 'wrestl', 'motoki', 'sakura'],
    ['pari', 'gold', 'freestylebi', 'historic'],
]

doc_frequency_test = compute_document_frequency(processed_text_test)
print(doc_frequency_test)

doc_frequency = compute_document_frequency(processed_text)

############################################################
#                    End of your code.                     #
############################################################

{'pari': 2, '2024': 1, 'gold': 3, 'wrestl': 2, 'sakura': 1, 'motoki': 1, 'freestylebi': 1, 'historic': 1}

In [264]:
vocab = list(doc_frequency.keys())
n_vocab = len(vocab)
n_docs = len(processed_text)

The next step is to convert the document to a vector representation ($\mathbb{R}^V$). Specifically, we will represent the document as a bag of words vector wherein the elements of the vector correspond to the tf-idf weights of each of the word (or token) in the vocabulary.

In [265]:
###############################################################
# TODO-21: Implement a function the convert a document to its #
# vector representation where each element contains the       #
# tf-idf of the corresponding word or token.                  #
###############################################################

import math

def document_to_tfidf_vector(doc, doc_frequency, vocab, n_docs):
    """
    Converts a document into its TF-IDF vector representation.

    Parameters:
    - doc: List of tokens (words) in the document.
    - doc_frequency: Dictionary containing document frequencies for tokens.
    - vocab: List of all unique tokens in the dataset (vocabulary).
    - n_docs: Total number of documents in the dataset.

    Returns:
    - A list representing the TF-IDF vector, with each element corresponding to a token in the vocabulary.
    """
    # Calculate term frequency (TF) for the document
    term_counts = {}
    for token in doc:
        if token in vocab:  # Only consider tokens in the vocabulary
            term_counts[token] = term_counts.get(token, 0) + 1

    total_terms = len(doc)

    # Initialize the TF-IDF vector
    tfidf_vector = []

    # Calculate TF-IDF for each token in the vocabulary
    for token in vocab:
        tf = term_counts.get(token, 0) / total_terms  # Term frequency
        idf = math.log((n_docs / (1 + doc_frequency.get(token, 0))), 10)  # Inverse document frequency
        tfidf = tf * idf  # TF-IDF score
        tfidf_vector.append(tfidf)

    return tfidf_vector

# Example doc_test (single document)
doc_test = ['pari', '2024', 'gold', 'wrestl', 'pari']

# Example doc_frequency_test dictionary
doc_frequency_test = {
    'pari': 2, '2024': 1, 'gold': 3, 'wrestl': 2, 
    'motoki': 1, 'sakura': 1, 'freestylebi': 1, 'historic': 1
}

# Example vocab_test
vocab_test = ['pari', '2024', 'gold', 'wrestl', 'motoki', 'sakura', 'freestylebi', 'historic']

# Total number of documents (n_docs_test)
n_docs_test = 3

# Generate TF-IDF vector for the single document
tfidf_vector_test = document_to_tfidf_vector(doc_test, doc_frequency_test, vocab_test, n_docs_test)

# Display the result
print("TF-IDF Vector for the single document (doc_test):")
print(tfidf_vector_test)

############################################################
#                    End of your code.                     #
############################################################

TF-IDF Vector for the single document (doc_test):
[0.0, 0.03521825181113625, -0.024987747321659988, 0.0, 0.0, 0.0, 0.0, 0.0]

For convenience of lookup later on, we compile all these document vectors into a matrix $\mathbb{R}^{N \times V}$, where each row is a document and the columns are the tokens / words.

In [266]:
doc_vectors = np.zeros((n_docs, n_vocab))
for doc_idx, doc in enumerate(processed_text):
    doc_vectors[doc_idx] = document_to_tfidf_vector(doc, doc_frequency, vocab, n_docs)

doc_vectors

array([[0.02230583, 0.00480735, 0.00108308, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.00263336, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.00107959, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.03032387, 0.03032387,
        0.03032387]])

Lastly, we need to compute the similarity of a query vector to all the documents and retrieve the most similar document. For this, we use the cosine similarity, the formula of which is shown below.

$$\text{cosine\_similarity}(a, b) = \frac{a^Tb}{\lVert a \rVert_2 \lVert b \rVert_2 } = \left ( \frac{a}{\lVert a \rVert_2} \right )^T \left( \frac{b}{\lVert b \rVert_2 } \right ) $$


In practice, we implement this computation by batch, meaning we compute the cosine similarities to all documents at once. Specifically, let the `doc_vector` be a matrix of size $\mathbb{R}^{N \times V}$ and the `query_vector` be of size $\mathbb{R}^{V \times 1}$, then the output of the `cosine_similarity` function is a vector of size $\mathbb{R}^{N}$ which contains the cosine similarity of the `query_vector` to all $N$ documents.

In [267]:
############################################################
# TODO-22: Implement a function that computes the cosine   #
# similarity of a query vector with shape (V,) to all      #
# document vectors with shape (N,  V). The output will be  #
# a vector of shape (N,) that represents the cosine        #
# similarity for each of the documents.                    #
############################################################
def cosine_similarity(doc_vectors, query_vector):
    """
    Computes the cosine similarity between a query vector and all document vectors.

    Args:
        doc_vectors (numpy.ndarray): 2D array with shape (N, V) where N is the number of documents.
        query_vector (numpy.ndarray): 1D array with shape (V,) representing the query vector.

    Returns:
        numpy.ndarray: 1D array with shape (N,) containing cosine similarity scores.
    """
    # Compute dot product between each document vector and the query vector
    dot_products = np.dot(doc_vectors, query_vector)

    # Compute the norms (magnitude) of document vectors and the query vector
    doc_norms = np.linalg.norm(doc_vectors, axis=1)
    query_norm = np.linalg.norm(query_vector)

    # Avoid division by zero by adding a small epsilon
    epsilon = 1e-10  # Small value to handle zero norms
    doc_norms = np.where(doc_norms == 0, epsilon, doc_norms)
    query_norm = max(query_norm, epsilon)

    # Calculate cosine similarity
    cosine_similarities = dot_products / (doc_norms * query_norm)

    return cosine_similarities

############################################################
#                    End of your code.                     #
############################################################

In [268]:
query1 = "who is michael phelps?"
query2 = "rules for swimming"
query3 = "when will swimming event happen?"
query4 = "most decorated american woman in olympic history."
query5 = "Athletes representing Saint Lucia and Dominica won their countries' first-ever Olympic medals."

In [269]:
############################################################
# TODO-23: Write a piece of code that retrieves the most   #
# similar document given a query. Print the query text and #
# the raw text of the corresponding document (hint: there  #
# should be a raw_doc_texts above that contains the list   #
# of raw document text)                                    #
#                                                          #
# Format the print as follows                              #
#                                                          #
# Query text: ....                                         #
# Retrieved document text: ...                             #
############################################################
import numpy as np

def retrieve_most_similar_document(queries, raw_doc_texts, doc_vectors, doc_frequency, vocab, n_docs):
    """
    Retrieves the most similar document for each query.

    Args:
        queries (list of str): List of query strings.
        raw_doc_texts (list of str): List of raw document texts.
        doc_vectors (numpy.ndarray): Array of TF-IDF vectors for all documents.
        doc_frequency (dict): Dictionary of document frequencies for the tokens.
        vocab (list of str): Vocabulary of all unique tokens.
        n_docs (int): Total number of documents.

    Returns:
        None. Prints the query and the most similar document.
    """
    for query in queries:
        # Preprocess the query to get tokens
        query_tokens = preprocess(query)
        
        # Convert query tokens into a TF-IDF vector
        query_vector = document_to_tfidf_vector(query_tokens, doc_frequency, vocab, n_docs)
        
        # Compute cosine similarity for the query and all document vectors
        similarities = cosine_similarity(doc_vectors, query_vector)
        
        # Find the index of the most similar document
        most_similar_idx = np.argmax(similarities)
        
        # Print the query and the most similar document
        print("Query text:", query)
        print("Retrieved document text:", raw_doc_texts[most_similar_idx])
        print()

# Example usage
queries = [query1, query2, query3, query4, query5]
retrieve_most_similar_document(queries, raw_doc_texts, doc_vectors, doc_frequency, vocab, n_docs)

############################################################
#                    End of your code.                     #
############################################################

Query text: who is michael phelps?
Retrieved document text: Michael PHELPSUnited States of AmericaSwimmingOlympic Medals23G3S2BGames Participations5First Olympic GamesSydney 2000Year of Birth1985Social MediaOlympic ResultsBiographyMichael Phelps is arguably the greatest Olympian ever. Some might argue that Usain Bolt, Carl Lewis or Nadia Comaneci have a claim. But for sheer numbers of medals claimed, there is a clear, hands-down winner: Michael Phelps. Even given the fact that Phelps practices a sport in which extremely capable athlete can bag golds across different distances and strokes, his feats still blow away those of any other sportsperson.
Phelps has 28 medals in total: his 23 gold medals are more than double the count of his nearest rivals, and its not as if other swimmers have accrued silly numbers of medals, either. Apart from Spitz, Matt Biondi (USA, eight golds) and Jenny Thompson (USA, eight golds), no other swimmer worldwide has managed more than six gold medals in total. 23 is astonishing.
Phelps was born in Baltimore on June 30, 1985, and got serious with the sport after joining the North Baltimore Aquatic Club. He was raised by mother Deborah, alongside his sisters Hilary and Whitney, after his parents divorced.A prodigy at his sport, he went to Sydney 2000 aged just 15 –the youngest man in the USA team for an Olympic Games in 68 years). He came close to the podium only in the 200m butterfly, where he finished fifth. From then on, he would dominate the next four Games, finishing the most decorated athlete at every one. In Athens he won six gold medals and two bronzes, falling just short of Mark Spitz’s world record (seven golds at Munich 1972).
Beijing 2008 would see the greatest ever medal haul by a single athlete in an Olympic Games. Phelps won eight golds – every event he entered – and broke World Records in seven of them. His record looks unlikely to be surpassed any time soon.
London 2012 was also astonishing – he got four golds and two silvers – while Rio 2016 saw him stage a historic comeback (he had decided to retire after London), aged 31, to bag five gold medals and one silver.
He is now retired and is married to Nicole, with whom he has three sons, Boomer, Becker, and Maverick. Phelps works for his own charitable foundation, which has a particular emphasis on the mental health of children.You can't put a limit on anything. The more you dream, the farther you get.”FeaturedMichael PHELPS32:33Michael Phelps II - All eight Gold Medal Races at Beijing 2008Beijing 2008 | Olympic GamesMichael PHELPSMichael Phelps: The man who dominated the Olympic pool like no otherMichael PHELPSOriginals05:56Michael Phelps' Record Eight Gold Medals in BeijingThe Olympics On the RecordMichael PHELPS ReplaysAll ReplaysAthens 2004Beijing 2008London 2012Rio 2016Olympic ResultsMore resultsAthlete Olympic Results ContentYou may like

Query text: rules for swimming
Retrieved document text: Olympic swimming rules: How can swimmers qualify for finals and win medals - format explainedBy Olympics.com7 min| Picture by Getty ImagesSwimming Swimming  is a sport that boasts a rich history at the modern Olympic Games, having featured at every edition since Athens 1896.
The inaugural Games saw competitions only in men’s freestyle swimming. The backstroke events were added at Paris 1900, breaststroke at St. Louis 1904 and butterfly at Melbourne 1956.
All four swimming strokes, along with the medley, are part of the programme at the Paris 2024 Olympics.
Having been contested in open water bodies for the first three Olympic Games, swimming events were held in the swimming pool for the first time at London 1908, a tradition that continues to this day.
Women’s swimming events were added to the Olympic programme at Stockholm 1912.
Overall, swimmers from the United States have dominated the Olympic pool and boast 580 Olympic medals, including 256 golds. Australia are second with a tally of 221 medals, including 71 golds.
USA’s Michael Phelps is the most decorated Olympian of all time. With 23 gold medals, three silvers and two bronzes, Phelps has won more than twice as many golds as his nearest rival and compatriot Mark Spitz, a nine-time Olympic gold medallist.
Swimming at Paris 2024 Olympics
A total of 854 athletes – 463 male and 391 female – from 187 countries, the Individual Neutral Athletes and the IOC Refugee Olympic Team, will compete at the Paris 2024 swimming events from July 27 to August 4 at the Paris La Defense Arena.
Each country could send at least two athletes to Paris through their NOC. Five countries – Dominica, Guinea-Bissau, Mauritania, Saint Kitts and Nevis and Vanuatu – will make their Olympic swimming debuts at Paris 2024.
Swimming at the Paris 2024 Olympics consists of individual events, team relay events (men and women separately) and a 4x100m medley relay for mixed teams. There are 35 events in total (17 women's, 17 men's and one mixed event). Each offers its own set of gold, silver and bronze medals.
Since the Tokyo 2020 Olympics, the women’s and men’s programmes have been identical.
Swimming events at Paris 2024 Olympics
Freestyle (men and women)

50m
100m
200m
400m
800m
1500m

Backstroke (men and women)

100m
200m

Breaststroke (men and women)

100m
200m

Butterfly (men and women)

100m
200m

Individual medley (men and women)

200m
400m

Team (men and women)

4x100m freestyle relay
4x200m freestyle relay
4x100m medley relay

Mixed event

4x100m medley relay

Paris 2024 Olympics swimming rules
Swimming at the Paris 2024 Olympics will be held per the rules of the World Aquatics Constitution and Rules and the Olympic Charter.
The criteria for ranking in any swimming event is the same. The swimmer who completes the course legally in the least amount of time finishes first and the rest are ordered according to their timings - quickest to slowest.
Individual events of 50m, 100m and 200m consist of heats, semi-finals and finals. The top 16 swimmers from the heats will advance to the semi-finals and the top eight from the semis will advance from the finals, where medals will be decided.
Individual events of 400m, 800m, 1500m and the team relay events consist of two phases - heats and finals. The top eight athletes or teams will advance from the heats to the final.
For all single-gender relay events, a team consists of four athletes. For the mixed relay event, a team consists of two men and two women.
Heats for all events take place in morning sessions. Semi-finals, finals and victory ceremonies take place in evening sessions.
Tiebreak rules
For individual events of 200m or less, ties for the last qualification or reserve position (from heats and semi-finals) may be broken by swim-offs. In longer distance events and relays, if athletes or teams are tied for the last qualification place, all tied athletes or teams will take part in the final (maximum of 10 lanes). If more than three athletes or teams are tied for the last qualification place, a swim-off may be held. There are no other tie-breaking rules for ranking.
Penalties/disqualification rules
The most common reasons for individual disqualification in swimming are false starts and illegal touches or kicks in breaststroke or butterfly.
In relays, a common infraction is an early start during the exchange as detected by the automatic judging equipment. Video technology was initially introduced to confirm or overturn infraction reports made from the pool deck. It is now also used to initiate infraction reports.
Protests/appeals
Protests may be filed against decisions taken by referees. Protests are accepted up to 30 minutes after the publication of the phase results of the event concerned or in the case of a video review, up to 30 minutes after the video review has taken place. The jury of appeal is the World Aquatics Bureau.
Differences between Swimming World Championships and Olympics
Some events are conducted at the Swimming World Championships that are not in the Olympics. These are 50m butterfly, 50m breaststroke and 50m backstroke for men and women, and a mixed 4x100m freestyle relay.
Olympic swimming pool size
The Olympic-sized swimming pools are 50-metre long and 25-metre wide with 10 lanes. As per World Aquatics, lanes shall be 2.5 metres wide with two spaces of 2.5 metres wide outside of lanes 1 and 8. The outside lanes are left empty to minimise the disadvantage caused by waves bouncing back off the side walls. There must be a rope separating each lane.
The 50-metre pool is typically referred to as a long-course swimming pool, distinguishing it from short course which applies to competitions in pools that are 25 metres in length.
Venue for swimming events at Paris 2024
Paris La Defense Arena will be the venue for swimming events for the Paris 2024 Olympics. The swimming pool at the venue is an Olympic-size 50-metre pool with 10 lanes. Swimming events will be held in the eight central lanes. Lanes zero and nine may also be used in the case of a tie.
Swimming terminologies

Call room: A room to which the athletes report before the race for final equipment checks and preparation.
Exchange: Occurs during relays when one athlete touches the wall and the next athlete dives in.
False start: Occurs when an athlete initiates a start before the starter officially starts the race.
Flip/tumble/turn: Used in freestyle and backstroke races, where athletes somersault before reaching the wall and push off with their feet, never touching the wall with their hands.
Lane lines/ropes: The dividers used to create lanes.
Lead-off athlete: The first athlete in a relay.
Leg: The portion of a relay swum by one team member.
Negative split: A race strategy in which a competitor swims the second half faster than the first.
Reaction time: The elapsed time between the starting signal of the race and the time the athlete leaves the starting block, or touchpad in backstroke races.
Reserve: The two non-qualifying athletes/teams with the fastest times are potential replacements for any qualifier that is unable to, or chooses not to, swim in the next round.
Splits: Intermediate times within a race.
Starting blocks: An elevated platform on the deck at the end of a lane from which the athlete starts an event, except in backstroke events when athletes start in the water.
Swimming strokes: There are four strokes - Freestyle, backstroke, breaststroke and butterfly. Individual medley is made up of equal portions of four strokes in the order of butterfly, backstroke, breaststroke, and freestyle.
Swim-off: An extra race used to determine which athletes or relay teams will advance to the semifinals, or final, in the case of a tie for the last qualifying position(s). A swim-off may also be held to determine reserve positions.
Touchpad: An electronic panel that is placed into the water at the end of a lane to record an athlete's intermediate or final time in an event.
Video judging: Overhead and underwater cameras around the competition pool, used by the referee and appointed judges to confirm and initiate rule-infraction reports.
Related content

Query text: when will swimming event happen?
Retrieved document text: Olympic swimming rules: How can swimmers qualify for finals and win medals - format explainedBy Olympics.com7 min| Picture by Getty ImagesSwimming Swimming  is a sport that boasts a rich history at the modern Olympic Games, having featured at every edition since Athens 1896.
The inaugural Games saw competitions only in men’s freestyle swimming. The backstroke events were added at Paris 1900, breaststroke at St. Louis 1904 and butterfly at Melbourne 1956.
All four swimming strokes, along with the medley, are part of the programme at the Paris 2024 Olympics.
Having been contested in open water bodies for the first three Olympic Games, swimming events were held in the swimming pool for the first time at London 1908, a tradition that continues to this day.
Women’s swimming events were added to the Olympic programme at Stockholm 1912.
Overall, swimmers from the United States have dominated the Olympic pool and boast 580 Olympic medals, including 256 golds. Australia are second with a tally of 221 medals, including 71 golds.
USA’s Michael Phelps is the most decorated Olympian of all time. With 23 gold medals, three silvers and two bronzes, Phelps has won more than twice as many golds as his nearest rival and compatriot Mark Spitz, a nine-time Olympic gold medallist.
Swimming at Paris 2024 Olympics
A total of 854 athletes – 463 male and 391 female – from 187 countries, the Individual Neutral Athletes and the IOC Refugee Olympic Team, will compete at the Paris 2024 swimming events from July 27 to August 4 at the Paris La Defense Arena.
Each country could send at least two athletes to Paris through their NOC. Five countries – Dominica, Guinea-Bissau, Mauritania, Saint Kitts and Nevis and Vanuatu – will make their Olympic swimming debuts at Paris 2024.
Swimming at the Paris 2024 Olympics consists of individual events, team relay events (men and women separately) and a 4x100m medley relay for mixed teams. There are 35 events in total (17 women's, 17 men's and one mixed event). Each offers its own set of gold, silver and bronze medals.
Since the Tokyo 2020 Olympics, the women’s and men’s programmes have been identical.
Swimming events at Paris 2024 Olympics
Freestyle (men and women)

50m
100m
200m
400m
800m
1500m

Backstroke (men and women)

100m
200m

Breaststroke (men and women)

100m
200m

Butterfly (men and women)

100m
200m

Individual medley (men and women)

200m
400m

Team (men and women)

4x100m freestyle relay
4x200m freestyle relay
4x100m medley relay

Mixed event

4x100m medley relay

Paris 2024 Olympics swimming rules
Swimming at the Paris 2024 Olympics will be held per the rules of the World Aquatics Constitution and Rules and the Olympic Charter.
The criteria for ranking in any swimming event is the same. The swimmer who completes the course legally in the least amount of time finishes first and the rest are ordered according to their timings - quickest to slowest.
Individual events of 50m, 100m and 200m consist of heats, semi-finals and finals. The top 16 swimmers from the heats will advance to the semi-finals and the top eight from the semis will advance from the finals, where medals will be decided.
Individual events of 400m, 800m, 1500m and the team relay events consist of two phases - heats and finals. The top eight athletes or teams will advance from the heats to the final.
For all single-gender relay events, a team consists of four athletes. For the mixed relay event, a team consists of two men and two women.
Heats for all events take place in morning sessions. Semi-finals, finals and victory ceremonies take place in evening sessions.
Tiebreak rules
For individual events of 200m or less, ties for the last qualification or reserve position (from heats and semi-finals) may be broken by swim-offs. In longer distance events and relays, if athletes or teams are tied for the last qualification place, all tied athletes or teams will take part in the final (maximum of 10 lanes). If more than three athletes or teams are tied for the last qualification place, a swim-off may be held. There are no other tie-breaking rules for ranking.
Penalties/disqualification rules
The most common reasons for individual disqualification in swimming are false starts and illegal touches or kicks in breaststroke or butterfly.
In relays, a common infraction is an early start during the exchange as detected by the automatic judging equipment. Video technology was initially introduced to confirm or overturn infraction reports made from the pool deck. It is now also used to initiate infraction reports.
Protests/appeals
Protests may be filed against decisions taken by referees. Protests are accepted up to 30 minutes after the publication of the phase results of the event concerned or in the case of a video review, up to 30 minutes after the video review has taken place. The jury of appeal is the World Aquatics Bureau.
Differences between Swimming World Championships and Olympics
Some events are conducted at the Swimming World Championships that are not in the Olympics. These are 50m butterfly, 50m breaststroke and 50m backstroke for men and women, and a mixed 4x100m freestyle relay.
Olympic swimming pool size
The Olympic-sized swimming pools are 50-metre long and 25-metre wide with 10 lanes. As per World Aquatics, lanes shall be 2.5 metres wide with two spaces of 2.5 metres wide outside of lanes 1 and 8. The outside lanes are left empty to minimise the disadvantage caused by waves bouncing back off the side walls. There must be a rope separating each lane.
The 50-metre pool is typically referred to as a long-course swimming pool, distinguishing it from short course which applies to competitions in pools that are 25 metres in length.
Venue for swimming events at Paris 2024
Paris La Defense Arena will be the venue for swimming events for the Paris 2024 Olympics. The swimming pool at the venue is an Olympic-size 50-metre pool with 10 lanes. Swimming events will be held in the eight central lanes. Lanes zero and nine may also be used in the case of a tie.
Swimming terminologies

Call room: A room to which the athletes report before the race for final equipment checks and preparation.
Exchange: Occurs during relays when one athlete touches the wall and the next athlete dives in.
False start: Occurs when an athlete initiates a start before the starter officially starts the race.
Flip/tumble/turn: Used in freestyle and backstroke races, where athletes somersault before reaching the wall and push off with their feet, never touching the wall with their hands.
Lane lines/ropes: The dividers used to create lanes.
Lead-off athlete: The first athlete in a relay.
Leg: The portion of a relay swum by one team member.
Negative split: A race strategy in which a competitor swims the second half faster than the first.
Reaction time: The elapsed time between the starting signal of the race and the time the athlete leaves the starting block, or touchpad in backstroke races.
Reserve: The two non-qualifying athletes/teams with the fastest times are potential replacements for any qualifier that is unable to, or chooses not to, swim in the next round.
Splits: Intermediate times within a race.
Starting blocks: An elevated platform on the deck at the end of a lane from which the athlete starts an event, except in backstroke events when athletes start in the water.
Swimming strokes: There are four strokes - Freestyle, backstroke, breaststroke and butterfly. Individual medley is made up of equal portions of four strokes in the order of butterfly, backstroke, breaststroke, and freestyle.
Swim-off: An extra race used to determine which athletes or relay teams will advance to the semifinals, or final, in the case of a tie for the last qualifying position(s). A swim-off may also be held to determine reserve positions.
Touchpad: An electronic panel that is placed into the water at the end of a lane to record an athlete's intermediate or final time in an event.
Video judging: Overhead and underwater cameras around the competition pool, used by the referee and appointed judges to confirm and initiate rule-infraction reports.
Related content

Query text: most decorated american woman in olympic history.
Retrieved document text: Paris 2024 tennis: Andy Murray bows out of Olympic doubles to draw the curtain on a decorated career By Ockert de Villiers2 min| Picture by Matthew Stockman/Getty ImagesAndy MURRAYTennis A visibly emotional Andy Murray waved at the Stade Roland-Garros crowd amid chants of "Murray! Murray! Murray!" as he brought the curtain down on a decorated tennis career on Thursday, 1 August at the Olympic Games Paris 2024.
Murray ran out of lives at Paris 2024 as his retirement finally arrived with a doubles defeat.
It was the end of the road for the tenacious Scot and men’s doubles partner Dan Evans at this year’s Olympics.

<span style='color:red'>**Question 04:**</span> Based on your results above, is there a difference between short queries or longer queries in terms of the quality of the retrievals? Explain why this might or might not be the case.

<span style='color:red'>**A04:**</span> Longer queries typically improve document retrieval quality by providing more context, which helps the system better match relevant documents. They offer clear details, enhance TF-IDF scoring accuracy, and increase precision by reducing irrelevant results. However, overly specific queries may narrow results too much, and some methods like semantic embeddings might handle shorter queries more effectively.

<span style='color:red'>**Question 05:**</span> Does this implementation capture grammar or sentence structure? Why or why not?

<span style='color:red'>**A05:**</span> This implementation does not account for grammar or sentence structure. Using the TF-IDF model, documents are treated as collections of unordered words (bags of words), focusing only on the frequency and importance of individual words across documents. Consequently, it does not consider the order of words or their syntactic relationships, which are crucial for understanding grammar and sentence structure.

<span style='color:red'>**Question:**</span> How much time did it take you to answer this notebook?

<span style='color:red'>**A:**</span> 16 hours

<span style='color:red'>**Question:**</span> What parts of the assignment did you like and what parts did you not like?

<span style='color:red'>**A:**</span> It is in general way too long. The bigram and tf-idf can also be unclear at times. The loading of articles was not always working properly.

<span style='color:red'>**Question:**</span> How do you think it could be improved?

<span style='color:red'>**A:**</span> Some Deep Learning addition work, but make it somewhat smaller. Maybe split off some of this part to other segments or assignment 1.

<span style='color:red'>**Question:**</span> Do you have any case studies in mind that would be nice to suggest / include in the assignment?

<span style='color:red'>**A:**</span> No